//------------------------------------------------------------------------------
//
// 说明：该文件中的内容是由代码生成器自动生成的，请勿手工修改！
//
// file name：IJISDataInputAccessor.autogenerated.cs
// author: mayanjun
// create date：2018-07-23 20:14:21
//
//------------------------------------------------------------------------------
using System;
using System.Collections;
using System.Collections.Generic;

namespace Book.DA
{
    public partial interface IJISDataInputAccessor
    {
        bool HasRows();
		
        bool HasRows(string id);
		
		Model.JISDataInput Get(string id);
		
		void Delete(string id);
		
		int Count();
		
		void Insert(Model.JISDataInput e);
		
		void Update(Model.JISDataInput e);
		
		IList<Model.JISDataInput> Select();
		
		IList<Model.JISDataInput> Select(Helper.OrderDescription orderDescription, Helper.PagingDescription pagingDescription);
		
		bool ExistsPrimary(string id);
		bool HasRowsBefore(Model.JISDataInput e);
		
		bool HasRowsAfter(Model.JISDataInput e);
		
		Model.JISDataInput GetFirst();
		
		Model.JISDataInput GetLast();
		
		Model.JISDataInput GetPrev(Model.JISDataInput e);
		
		Model.JISDataInput GetNext(Model.JISDataInput e);

	}
}
