//------------------------------------------------------------------------------
//
// 说明：该文件中的内容是由代码生成器自动生成的，请勿手工修改！
//
// file name：IPCAssemblyInspectionAccessor.autogenerated.cs
// author: mayanjun
// create date：2017-11-05 16:28:12
//
//------------------------------------------------------------------------------
using System;
using System.Collections;
using System.Collections.Generic;

namespace Book.DA
{
    public partial interface IPCAssemblyInspectionAccessor
    {
        bool HasRows();
		
        bool HasRows(string id);
		
		Model.PCAssemblyInspection Get(string id);
		
		void Delete(string id);
		
		int Count();
		
		void Insert(Model.PCAssemblyInspection e);
		
		void Update(Model.PCAssemblyInspection e);
		
		IList<Model.PCAssemblyInspection> Select();
		
		IList<Model.PCAssemblyInspection> Select(Helper.OrderDescription orderDescription, Helper.PagingDescription pagingDescription);
		
		bool ExistsPrimary(string id);
		bool HasRowsBefore(Model.PCAssemblyInspection e);
		
		bool HasRowsAfter(Model.PCAssemblyInspection e);
		
		Model.PCAssemblyInspection GetFirst();
		
		Model.PCAssemblyInspection GetLast();
		
		Model.PCAssemblyInspection GetPrev(Model.PCAssemblyInspection e);
		
		Model.PCAssemblyInspection GetNext(Model.PCAssemblyInspection e);

	}
}
