//------------------------------------------------------------------------------
//
// 说明：该文件中的内容是由代码生成器自动生成的，请勿手工修改！
//
// file name：IPCAssemblyInspectionDetailAccessor.autogenerated.cs
// author: mayanjun
// create date：2017-11-05 16:28:12
//
//------------------------------------------------------------------------------
using System;
using System.Collections;
using System.Collections.Generic;

namespace Book.DA
{
    public partial interface IPCAssemblyInspectionDetailAccessor
    {
        bool HasRows();
		
        bool HasRows(string id);
		
		Model.PCAssemblyInspectionDetail Get(string id);
		
		void Delete(string id);
		
		int Count();
		
		void Insert(Model.PCAssemblyInspectionDetail e);
		
		void Update(Model.PCAssemblyInspectionDetail e);
		
		IList<Model.PCAssemblyInspectionDetail> Select();
		
		IList<Model.PCAssemblyInspectionDetail> Select(Helper.OrderDescription orderDescription, Helper.PagingDescription pagingDescription);
		
		bool ExistsPrimary(string id);

	}
}
