//------------------------------------------------------------------------------
//
// 说明：该文件中的内容是由代码生成器自动生成的，请勿手工修改！
//
// file name：IPCDataInputAccessor.autogenerated.cs
// author: mayanjun
// create date：2015/1/18 下午 08:12:16
//
//------------------------------------------------------------------------------
using System;
using System.Collections;
using System.Collections.Generic;

namespace Book.DA
{
    public partial interface IPCDataInputAccessor
    {
        bool HasRows();
		
        bool HasRows(string id);
		
		Model.PCDataInput Get(string id);
		
		void Delete(string id);
		
		int Count();
		
		void Insert(Model.PCDataInput e);
		
		void Update(Model.PCDataInput e);
		
		IList<Model.PCDataInput> Select();
		
		IList<Model.PCDataInput> Select(Helper.OrderDescription orderDescription, Helper.PagingDescription pagingDescription);
		
		bool ExistsPrimary(string id);
		bool HasRowsBefore(Model.PCDataInput e);
		
		bool HasRowsAfter(Model.PCDataInput e);
		
		Model.PCDataInput GetFirst();
		
		Model.PCDataInput GetLast();
		
		Model.PCDataInput GetPrev(Model.PCDataInput e);
		
		Model.PCDataInput GetNext(Model.PCDataInput e);

	}
}
