//------------------------------------------------------------------------------
//
// 说明：该文件中的内容是由代码生成器自动生成的，请勿手工修改！
//
// file name：IPCEarplugsStayWireCheckDetailAccessor.autogenerated.cs
// author: mayanjun
// create date：2019/5/14 10:01:26
//
//------------------------------------------------------------------------------
using System;
using System.Collections;
using System.Collections.Generic;

namespace Book.DA
{
    public partial interface IPCEarplugsStayWireCheckDetailAccessor
    {
        bool HasRows();
		
        bool HasRows(string id);
		
		Model.PCEarplugsStayWireCheckDetail Get(string id);
		
		void Delete(string id);
		
		int Count();
		
		void Insert(Model.PCEarplugsStayWireCheckDetail e);
		
		void Update(Model.PCEarplugsStayWireCheckDetail e);
		
		IList<Model.PCEarplugsStayWireCheckDetail> Select();
		
		IList<Model.PCEarplugsStayWireCheckDetail> Select(Helper.OrderDescription orderDescription, Helper.PagingDescription pagingDescription);
		
		bool ExistsPrimary(string id);

	}
}
