//------------------------------------------------------------------------------
//
// 说明：该文件中的内容是由代码生成器自动生成的，请勿手工修改！
//
// file name：IPCEarplugsDecibelCheckAccessor.autogenerated.cs
// author: mayanjun
// create date：2019/5/12 14:43:54
//
//------------------------------------------------------------------------------
using System;
using System.Collections;
using System.Collections.Generic;

namespace Book.DA
{
    public partial interface IPCEarplugsDecibelCheckAccessor
    {
        bool HasRows();
		
        bool HasRows(string id);
		
		Model.PCEarplugsDecibelCheck Get(string id);
		
		void Delete(string id);
		
		int Count();
		
		void Insert(Model.PCEarplugsDecibelCheck e);
		
		void Update(Model.PCEarplugsDecibelCheck e);
		
		IList<Model.PCEarplugsDecibelCheck> Select();
		
		IList<Model.PCEarplugsDecibelCheck> Select(Helper.OrderDescription orderDescription, Helper.PagingDescription pagingDescription);
		
		bool ExistsPrimary(string id);
		bool HasRowsBefore(Model.PCEarplugsDecibelCheck e);
		
		bool HasRowsAfter(Model.PCEarplugsDecibelCheck e);
		
		Model.PCEarplugsDecibelCheck GetFirst();
		
		Model.PCEarplugsDecibelCheck GetLast();
		
		Model.PCEarplugsDecibelCheck GetPrev(Model.PCEarplugsDecibelCheck e);
		
		Model.PCEarplugsDecibelCheck GetNext(Model.PCEarplugsDecibelCheck e);

	}
}
