//------------------------------------------------------------------------------
//
// 说明：该文件中的内容是由代码生成器自动生成的，请勿手工修改！
//
// file name：IPCEarplugsResilienceWeightAccessor.autogenerated.cs
// author: mayanjun
// create date：2019/8/25 22:18:53
//
//------------------------------------------------------------------------------
using System;
using System.Collections;
using System.Collections.Generic;

namespace Book.DA
{
    public partial interface IPCEarplugsResilienceWeightAccessor
    {
        bool HasRows();
		
        bool HasRows(string id);
		
		Model.PCEarplugsResilienceWeight Get(string id);
		
		void Delete(string id);
		
		int Count();
		
		void Insert(Model.PCEarplugsResilienceWeight e);
		
		void Update(Model.PCEarplugsResilienceWeight e);
		
		IList<Model.PCEarplugsResilienceWeight> Select();
		
		IList<Model.PCEarplugsResilienceWeight> Select(Helper.OrderDescription orderDescription, Helper.PagingDescription pagingDescription);
		
		bool ExistsPrimary(string id);
		bool HasRowsBefore(Model.PCEarplugsResilienceWeight e);
		
		bool HasRowsAfter(Model.PCEarplugsResilienceWeight e);
		
		Model.PCEarplugsResilienceWeight GetFirst();
		
		Model.PCEarplugsResilienceWeight GetLast();
		
		Model.PCEarplugsResilienceWeight GetPrev(Model.PCEarplugsResilienceWeight e);
		
		Model.PCEarplugsResilienceWeight GetNext(Model.PCEarplugsResilienceWeight e);

	}
}
