//------------------------------------------------------------------------------
//
// 说明：该文件中的内容是由代码生成器自动生成的，请勿手工修改！
//
// file name：IPCEarplugsResilienceCheckAccessor.autogenerated.cs
// author: mayanjun
// create date：2019/5/10 10:49:43
//
//------------------------------------------------------------------------------
using System;
using System.Collections;
using System.Collections.Generic;

namespace Book.DA
{
    public partial interface IPCEarplugsResilienceCheckAccessor
    {
        bool HasRows();
		
        bool HasRows(string id);
		
		Model.PCEarplugsResilienceCheck Get(string id);
		
		void Delete(string id);
		
		int Count();
		
		void Insert(Model.PCEarplugsResilienceCheck e);
		
		void Update(Model.PCEarplugsResilienceCheck e);
		
		IList<Model.PCEarplugsResilienceCheck> Select();
		
		IList<Model.PCEarplugsResilienceCheck> Select(Helper.OrderDescription orderDescription, Helper.PagingDescription pagingDescription);
		
		bool ExistsPrimary(string id);
		bool HasRowsBefore(Model.PCEarplugsResilienceCheck e);
		
		bool HasRowsAfter(Model.PCEarplugsResilienceCheck e);
		
		Model.PCEarplugsResilienceCheck GetFirst();
		
		Model.PCEarplugsResilienceCheck GetLast();
		
		Model.PCEarplugsResilienceCheck GetPrev(Model.PCEarplugsResilienceCheck e);
		
		Model.PCEarplugsResilienceCheck GetNext(Model.PCEarplugsResilienceCheck e);

	}
}
