//------------------------------------------------------------------------------
//
// 说明：该文件中的内容是由代码生成器自动生成的，请勿手工修改！
//
// file name：IPCEarplugsResilienceCheckDetailAccessor.autogenerated.cs
// author: mayanjun
// create date：2019/5/10 10:49:43
//
//------------------------------------------------------------------------------
using System;
using System.Collections;
using System.Collections.Generic;

namespace Book.DA
{
    public partial interface IPCEarplugsResilienceCheckDetailAccessor
    {
        bool HasRows();
		
        bool HasRows(string id);
		
		Model.PCEarplugsResilienceCheckDetail Get(string id);
		
		void Delete(string id);
		
		int Count();
		
		void Insert(Model.PCEarplugsResilienceCheckDetail e);
		
		void Update(Model.PCEarplugsResilienceCheckDetail e);
		
		IList<Model.PCEarplugsResilienceCheckDetail> Select();
		
		IList<Model.PCEarplugsResilienceCheckDetail> Select(Helper.OrderDescription orderDescription, Helper.PagingDescription pagingDescription);
		
		bool ExistsPrimary(string id);

	}
}
