//------------------------------------------------------------------------------
//
// 说明：该文件中的内容是由代码生成器自动生成的，请勿手工修改！
//
// file name：IPCEarplugsStayWireCheckAccessor.autogenerated.cs
// author: mayanjun
// create date：2019/5/14 09:57:06
//
//------------------------------------------------------------------------------
using System;
using System.Collections;
using System.Collections.Generic;

namespace Book.DA
{
    public partial interface IPCEarplugsStayWireCheckAccessor
    {
        bool HasRows();
		
        bool HasRows(string id);
		
		Model.PCEarplugsStayWireCheck Get(string id);
		
		void Delete(string id);
		
		int Count();
		
		void Insert(Model.PCEarplugsStayWireCheck e);
		
		void Update(Model.PCEarplugsStayWireCheck e);
		
		IList<Model.PCEarplugsStayWireCheck> Select();
		
		IList<Model.PCEarplugsStayWireCheck> Select(Helper.OrderDescription orderDescription, Helper.PagingDescription pagingDescription);
		
		bool ExistsPrimary(string id);
		bool HasRowsBefore(Model.PCEarplugsStayWireCheck e);
		
		bool HasRowsAfter(Model.PCEarplugsStayWireCheck e);
		
		Model.PCEarplugsStayWireCheck GetFirst();
		
		Model.PCEarplugsStayWireCheck GetLast();
		
		Model.PCEarplugsStayWireCheck GetPrev(Model.PCEarplugsStayWireCheck e);
		
		Model.PCEarplugsStayWireCheck GetNext(Model.PCEarplugsStayWireCheck e);

	}
}
