//------------------------------------------------------------------------------
//
// 说明：该文件中的内容是由代码生成器自动生成的，请勿手工修改！
//
// file name：IPCEarplugsResilienceConditionSetAccessor.autogenerated.cs
// author: mayanjun
// create date：2019/6/15 19:29:48
//
//------------------------------------------------------------------------------
using System;
using System.Collections;
using System.Collections.Generic;

namespace Book.DA
{
    public partial interface IPCEarplugsResilienceConditionSetAccessor
    {
        bool HasRows();
		
        bool HasRows(string id);
		
		Model.PCEarplugsResilienceConditionSet Get(string id);
		
		void Delete(string id);
		
		int Count();
		
		void Insert(Model.PCEarplugsResilienceConditionSet e);
		
		void Update(Model.PCEarplugsResilienceConditionSet e);
		
		IList<Model.PCEarplugsResilienceConditionSet> Select();
		
		IList<Model.PCEarplugsResilienceConditionSet> Select(Helper.OrderDescription orderDescription, Helper.PagingDescription pagingDescription);
		
		bool ExistsPrimary(string id);
		bool HasRowsBefore(Model.PCEarplugsResilienceConditionSet e);
		
		bool HasRowsAfter(Model.PCEarplugsResilienceConditionSet e);
		
		Model.PCEarplugsResilienceConditionSet GetFirst();
		
		Model.PCEarplugsResilienceConditionSet GetLast();
		
		Model.PCEarplugsResilienceConditionSet GetPrev(Model.PCEarplugsResilienceConditionSet e);
		
		Model.PCEarplugsResilienceConditionSet GetNext(Model.PCEarplugsResilienceConditionSet e);

	}
}
