//------------------------------------------------------------------------------
//
// 说明：该文件中的内容是由代码生成器自动生成的，请勿手工修改！
//
// file name：IPCPerspectiveAccessor.autogenerated.cs
// author: mayanjun
// create date：2015/1/18 下午 08:12:16
//
//------------------------------------------------------------------------------
using System;
using System.Collections;
using System.Collections.Generic;

namespace Book.DA
{
    public partial interface IPCPerspectiveAccessor
    {
        bool HasRows();
		
        bool HasRows(string id);
		
		Model.PCPerspective Get(string id);
		
		void Delete(string id);
		
		int Count();
		
		void Insert(Model.PCPerspective e);
		
		void Update(Model.PCPerspective e);
		
		IList<Model.PCPerspective> Select();
		
		IList<Model.PCPerspective> Select(Helper.OrderDescription orderDescription, Helper.PagingDescription pagingDescription);
		
		bool ExistsPrimary(string id);

	}
}
