//------------------------------------------------------------------------------
//
// 说明： 该文件中的内容是由代码生成器自动生成的，请勿手工修改！
//
// file name：BillIdSetAccessor.autogenerated.cs
// author: mayanjun
// create date：2015/11/20 18:57:00
//
//------------------------------------------------------------------------------
using System;
using System.Collections;
using System.Collections.Generic;
using System.Data;
using System.Data.SqlClient;
using System.Text;

namespace Book.DA.SQLServer
{
    public partial class BillIdSetAccessor
    {
		public Model.BillIdSet Get(string id)
		{
			return this.Get<Model.BillIdSet>(id);
		}
		
		public void Insert(Model.BillIdSet e)
		{
			this.Insert<Model.BillIdSet>(e);
		}
		
		public void Update(Model.BillIdSet e)
		{
			this.Update<Model.BillIdSet>(e);
		}
		
		public IList<Model.BillIdSet> Select()
		{
			return this.Select<Model.BillIdSet>();
		}
		
		public IList<Model.BillIdSet> Select(Helper.OrderDescription orderDescription, Helper.PagingDescription pagingDescription)
		{
			return this.Select<Model.BillIdSet>(orderDescription,pagingDescription);
		}
		public void Delete(string id)
		{
			this.Delete<Model.BillIdSet>(id);
		}
		public bool HasRows(string id)
		{
			return this.HasRows<Model.BillIdSet>(id);
		}
		public bool HasRows()
		{
			return this.HasRows<Model.BillIdSet>();
		}
		public int Count()
		{
			return this.Count<Model.BillIdSet>();
		}
		public bool HasRowsBefore(Model.BillIdSet e)
		{
			return sqlmapper.QueryForObject<bool>("BillIdSet.has_rows_before", e);
		}
		public bool HasRowsAfter(Model.BillIdSet e)
		{
			return sqlmapper.QueryForObject<bool>("BillIdSet.has_rows_after", e);
		}
		public Model.BillIdSet GetFirst()
		{
			return sqlmapper.QueryForObject<Model.BillIdSet>("BillIdSet.get_first", null);
		}
		public Model.BillIdSet GetLast()
		{
			return sqlmapper.QueryForObject<Model.BillIdSet>("BillIdSet.get_last", null);
		}
		public Model.BillIdSet GetNext(Model.BillIdSet e)
		{
			return sqlmapper.QueryForObject<Model.BillIdSet>("BillIdSet.get_next", e);
		}
		public Model.BillIdSet GetPrev(Model.BillIdSet e)
		{
			return sqlmapper.QueryForObject<Model.BillIdSet>("BillIdSet.get_prev", e);
		}
		

		public bool ExistsPrimary(string id)
		{			
			return sqlmapper.QueryForObject<bool>("BillIdSet.existsPrimary", id);
		}
    }
}
