//------------------------------------------------------------------------------
//
// 说明： 该文件中的内容是由代码生成器自动生成的，请勿手工修改！
//
// file name：BillIdDeletedAccessor.autogenerated.cs
// author: mayanjun
// create date：2015/11/20 18:57:00
//
//------------------------------------------------------------------------------
using System;
using System.Collections;
using System.Collections.Generic;
using System.Data;
using System.Data.SqlClient;
using System.Text;

namespace Book.DA.SQLServer
{
    public partial class BillIdDeletedAccessor
    {
		public Model.BillIdDeleted Get(string id)
		{
			return this.Get<Model.BillIdDeleted>(id);
		}
		
		public void Insert(Model.BillIdDeleted e)
		{
			this.Insert<Model.BillIdDeleted>(e);
		}
		
		public void Update(Model.BillIdDeleted e)
		{
			this.Update<Model.BillIdDeleted>(e);
		}
		
		public IList<Model.BillIdDeleted> Select()
		{
			return this.Select<Model.BillIdDeleted>();
		}
		
		public IList<Model.BillIdDeleted> Select(Helper.OrderDescription orderDescription, Helper.PagingDescription pagingDescription)
		{
			return this.Select<Model.BillIdDeleted>(orderDescription,pagingDescription);
		}
		public void Delete(string id)
		{
			this.Delete<Model.BillIdDeleted>(id);
		}
		public bool HasRows(string id)
		{
			return this.HasRows<Model.BillIdDeleted>(id);
		}
		public bool HasRows()
		{
			return this.HasRows<Model.BillIdDeleted>();
		}
		public int Count()
		{
			return this.Count<Model.BillIdDeleted>();
		}

		public bool ExistsPrimary(string id)
		{			
			return sqlmapper.QueryForObject<bool>("BillIdDeleted.existsPrimary", id);
		}
    }
}
