//------------------------------------------------------------------------------
//
// 说明： 该文件中的内容是由代码生成器自动生成的，请勿手工修改！
//
// file name：JISDataInputAccessor.autogenerated.cs
// author: mayanjun
// create date：2018-07-23 20:14:21
//
//------------------------------------------------------------------------------
using System;
using System.Collections;
using System.Collections.Generic;
using System.Data;
using System.Data.SqlClient;
using System.Text;

namespace Book.DA.SQLServer
{
    public partial class JISDataInputAccessor
    {
		public Model.JISDataInput Get(string id)
		{
			return this.Get<Model.JISDataInput>(id);
		}
		
		public void Insert(Model.JISDataInput e)
		{
			this.Insert<Model.JISDataInput>(e);
		}
		
		public void Update(Model.JISDataInput e)
		{
			this.Update<Model.JISDataInput>(e);
		}
		
		public IList<Model.JISDataInput> Select()
		{
			return this.Select<Model.JISDataInput>();
		}
		
		public IList<Model.JISDataInput> Select(Helper.OrderDescription orderDescription, Helper.PagingDescription pagingDescription)
		{
			return this.Select<Model.JISDataInput>(orderDescription,pagingDescription);
		}
		public void Delete(string id)
		{
			this.Delete<Model.JISDataInput>(id);
		}
		public bool HasRows(string id)
		{
			return this.HasRows<Model.JISDataInput>(id);
		}
		public bool HasRows()
		{
			return this.HasRows<Model.JISDataInput>();
		}
		public int Count()
		{
			return this.Count<Model.JISDataInput>();
		}
		public bool HasRowsBefore(Model.JISDataInput e)
		{
			return sqlmapper.QueryForObject<bool>("JISDataInput.has_rows_before", e);
		}
		public bool HasRowsAfter(Model.JISDataInput e)
		{
			return sqlmapper.QueryForObject<bool>("JISDataInput.has_rows_after", e);
		}
		public Model.JISDataInput GetFirst()
		{
			return sqlmapper.QueryForObject<Model.JISDataInput>("JISDataInput.get_first", null);
		}
		public Model.JISDataInput GetLast()
		{
			return sqlmapper.QueryForObject<Model.JISDataInput>("JISDataInput.get_last", null);
		}
		public Model.JISDataInput GetNext(Model.JISDataInput e)
		{
			return sqlmapper.QueryForObject<Model.JISDataInput>("JISDataInput.get_next", e);
		}
		public Model.JISDataInput GetPrev(Model.JISDataInput e)
		{
			return sqlmapper.QueryForObject<Model.JISDataInput>("JISDataInput.get_prev", e);
		}
		

		public bool ExistsPrimary(string id)
		{			
			return sqlmapper.QueryForObject<bool>("JISDataInput.existsPrimary", id);
		}
    }
}
