//------------------------------------------------------------------------------
//
// 说明： 该文件中的内容是由代码生成器自动生成的，请勿手工修改！
//
// file name：PCAssemblyInspectionAccessor.autogenerated.cs
// author: mayanjun
// create date：2017-11-05 16:28:12
//
//------------------------------------------------------------------------------
using System;
using System.Collections;
using System.Collections.Generic;
using System.Data;
using System.Data.SqlClient;
using System.Text;

namespace Book.DA.SQLServer
{
    public partial class PCAssemblyInspectionAccessor
    {
		public Model.PCAssemblyInspection Get(string id)
		{
			return this.Get<Model.PCAssemblyInspection>(id);
		}
		
		public void Insert(Model.PCAssemblyInspection e)
		{
			this.Insert<Model.PCAssemblyInspection>(e);
		}
		
		public void Update(Model.PCAssemblyInspection e)
		{
			this.Update<Model.PCAssemblyInspection>(e);
		}
		
		public IList<Model.PCAssemblyInspection> Select()
		{
			return this.Select<Model.PCAssemblyInspection>();
		}
		
		public IList<Model.PCAssemblyInspection> Select(Helper.OrderDescription orderDescription, Helper.PagingDescription pagingDescription)
		{
			return this.Select<Model.PCAssemblyInspection>(orderDescription,pagingDescription);
		}
		public void Delete(string id)
		{
			this.Delete<Model.PCAssemblyInspection>(id);
		}
		public bool HasRows(string id)
		{
			return this.HasRows<Model.PCAssemblyInspection>(id);
		}
		public bool HasRows()
		{
			return this.HasRows<Model.PCAssemblyInspection>();
		}
		public int Count()
		{
			return this.Count<Model.PCAssemblyInspection>();
		}
		public bool HasRowsBefore(Model.PCAssemblyInspection e)
		{
			return sqlmapper.QueryForObject<bool>("PCAssemblyInspection.has_rows_before", e);
		}
		public bool HasRowsAfter(Model.PCAssemblyInspection e)
		{
			return sqlmapper.QueryForObject<bool>("PCAssemblyInspection.has_rows_after", e);
		}
		public Model.PCAssemblyInspection GetFirst()
		{
			return sqlmapper.QueryForObject<Model.PCAssemblyInspection>("PCAssemblyInspection.get_first", null);
		}
		public Model.PCAssemblyInspection GetLast()
		{
			return sqlmapper.QueryForObject<Model.PCAssemblyInspection>("PCAssemblyInspection.get_last", null);
		}
		public Model.PCAssemblyInspection GetNext(Model.PCAssemblyInspection e)
		{
			return sqlmapper.QueryForObject<Model.PCAssemblyInspection>("PCAssemblyInspection.get_next", e);
		}
		public Model.PCAssemblyInspection GetPrev(Model.PCAssemblyInspection e)
		{
			return sqlmapper.QueryForObject<Model.PCAssemblyInspection>("PCAssemblyInspection.get_prev", e);
		}
		

		public bool ExistsPrimary(string id)
		{			
			return sqlmapper.QueryForObject<bool>("PCAssemblyInspection.existsPrimary", id);
		}
    }
}
