//------------------------------------------------------------------------------
//
// 说明： 该文件中的内容是由代码生成器自动生成的，请勿手工修改！
//
// file name：PCAssemblyInspectionDetailAccessor.autogenerated.cs
// author: mayanjun
// create date：2017-11-05 16:28:12
//
//------------------------------------------------------------------------------
using System;
using System.Collections;
using System.Collections.Generic;
using System.Data;
using System.Data.SqlClient;
using System.Text;

namespace Book.DA.SQLServer
{
    public partial class PCAssemblyInspectionDetailAccessor
    {
		public Model.PCAssemblyInspectionDetail Get(string id)
		{
			return this.Get<Model.PCAssemblyInspectionDetail>(id);
		}
		
		public void Insert(Model.PCAssemblyInspectionDetail e)
		{
			this.Insert<Model.PCAssemblyInspectionDetail>(e);
		}
		
		public void Update(Model.PCAssemblyInspectionDetail e)
		{
			this.Update<Model.PCAssemblyInspectionDetail>(e);
		}
		
		public IList<Model.PCAssemblyInspectionDetail> Select()
		{
			return this.Select<Model.PCAssemblyInspectionDetail>();
		}
		
		public IList<Model.PCAssemblyInspectionDetail> Select(Helper.OrderDescription orderDescription, Helper.PagingDescription pagingDescription)
		{
			return this.Select<Model.PCAssemblyInspectionDetail>(orderDescription,pagingDescription);
		}
		public void Delete(string id)
		{
			this.Delete<Model.PCAssemblyInspectionDetail>(id);
		}
		public bool HasRows(string id)
		{
			return this.HasRows<Model.PCAssemblyInspectionDetail>(id);
		}
		public bool HasRows()
		{
			return this.HasRows<Model.PCAssemblyInspectionDetail>();
		}
		public int Count()
		{
			return this.Count<Model.PCAssemblyInspectionDetail>();
		}

		public bool ExistsPrimary(string id)
		{			
			return sqlmapper.QueryForObject<bool>("PCAssemblyInspectionDetail.existsPrimary", id);
		}
    }
}
