//------------------------------------------------------------------------------
//
// 说明： 该文件中的内容是由代码生成器自动生成的，请勿手工修改！
//
// file name：PCDefinitionAccessor.autogenerated.cs
// author: mayanjun
// create date：2015/1/18 下午 08:12:17
//
//------------------------------------------------------------------------------
using System;
using System.Collections;
using System.Collections.Generic;
using System.Data;
using System.Data.SqlClient;
using System.Text;

namespace Book.DA.SQLServer
{
    public partial class PCDefinitionAccessor
    {
		public Model.PCDefinition Get(string id)
		{
			return this.Get<Model.PCDefinition>(id);
		}
		
		public void Insert(Model.PCDefinition e)
		{
			this.Insert<Model.PCDefinition>(e);
		}
		
		public void Update(Model.PCDefinition e)
		{
			this.Update<Model.PCDefinition>(e);
		}
		
		public IList<Model.PCDefinition> Select()
		{
			return this.Select<Model.PCDefinition>();
		}
		
		public IList<Model.PCDefinition> Select(Helper.OrderDescription orderDescription, Helper.PagingDescription pagingDescription)
		{
			return this.Select<Model.PCDefinition>(orderDescription,pagingDescription);
		}
		public void Delete(string id)
		{
			this.Delete<Model.PCDefinition>(id);
		}
		public bool HasRows(string id)
		{
			return this.HasRows<Model.PCDefinition>(id);
		}
		public bool HasRows()
		{
			return this.HasRows<Model.PCDefinition>();
		}
		public int Count()
		{
			return this.Count<Model.PCDefinition>();
		}

		public bool ExistsPrimary(string id)
		{			
			return sqlmapper.QueryForObject<bool>("PCDefinition.existsPrimary", id);
		}
    }
}
