//------------------------------------------------------------------------------
//
// 说明： 该文件中的内容是由代码生成器自动生成的，请勿手工修改！
//
// file name：PCEarplugsResilienceWeightAccessor.autogenerated.cs
// author: mayanjun
// create date：2019/8/25 22:18:54
//
//------------------------------------------------------------------------------
using System;
using System.Collections;
using System.Collections.Generic;
using System.Data;
using System.Data.SqlClient;
using System.Text;

namespace Book.DA.SQLServer
{
    public partial class PCEarplugsResilienceWeightAccessor
    {
		public Model.PCEarplugsResilienceWeight Get(string id)
		{
			return this.Get<Model.PCEarplugsResilienceWeight>(id);
		}
		
		public void Insert(Model.PCEarplugsResilienceWeight e)
		{
			this.Insert<Model.PCEarplugsResilienceWeight>(e);
		}
		
		public void Update(Model.PCEarplugsResilienceWeight e)
		{
			this.Update<Model.PCEarplugsResilienceWeight>(e);
		}
		
		public IList<Model.PCEarplugsResilienceWeight> Select()
		{
			return this.Select<Model.PCEarplugsResilienceWeight>();
		}
		
		public IList<Model.PCEarplugsResilienceWeight> Select(Helper.OrderDescription orderDescription, Helper.PagingDescription pagingDescription)
		{
			return this.Select<Model.PCEarplugsResilienceWeight>(orderDescription,pagingDescription);
		}
		public void Delete(string id)
		{
			this.Delete<Model.PCEarplugsResilienceWeight>(id);
		}
		public bool HasRows(string id)
		{
			return this.HasRows<Model.PCEarplugsResilienceWeight>(id);
		}
		public bool HasRows()
		{
			return this.HasRows<Model.PCEarplugsResilienceWeight>();
		}
		public int Count()
		{
			return this.Count<Model.PCEarplugsResilienceWeight>();
		}
		public bool HasRowsBefore(Model.PCEarplugsResilienceWeight e)
		{
			return sqlmapper.QueryForObject<bool>("PCEarplugsResilienceWeight.has_rows_before", e);
		}
		public bool HasRowsAfter(Model.PCEarplugsResilienceWeight e)
		{
			return sqlmapper.QueryForObject<bool>("PCEarplugsResilienceWeight.has_rows_after", e);
		}
		public Model.PCEarplugsResilienceWeight GetFirst()
		{
			return sqlmapper.QueryForObject<Model.PCEarplugsResilienceWeight>("PCEarplugsResilienceWeight.get_first", null);
		}
		public Model.PCEarplugsResilienceWeight GetLast()
		{
			return sqlmapper.QueryForObject<Model.PCEarplugsResilienceWeight>("PCEarplugsResilienceWeight.get_last", null);
		}
		public Model.PCEarplugsResilienceWeight GetNext(Model.PCEarplugsResilienceWeight e)
		{
			return sqlmapper.QueryForObject<Model.PCEarplugsResilienceWeight>("PCEarplugsResilienceWeight.get_next", e);
		}
		public Model.PCEarplugsResilienceWeight GetPrev(Model.PCEarplugsResilienceWeight e)
		{
			return sqlmapper.QueryForObject<Model.PCEarplugsResilienceWeight>("PCEarplugsResilienceWeight.get_prev", e);
		}
		

		public bool ExistsPrimary(string id)
		{			
			return sqlmapper.QueryForObject<bool>("PCEarplugsResilienceWeight.existsPrimary", id);
		}
    }
}
