//------------------------------------------------------------------------------
//
// 说明： 该文件中的内容是由代码生成器自动生成的，请勿手工修改！
//
// file name：PCEarplugsDecibelCheckAccessor.autogenerated.cs
// author: mayanjun
// create date：2019/5/12 14:43:54
//
//------------------------------------------------------------------------------
using System;
using System.Collections;
using System.Collections.Generic;
using System.Data;
using System.Data.SqlClient;
using System.Text;

namespace Book.DA.SQLServer
{
    public partial class PCEarplugsDecibelCheckAccessor
    {
		public Model.PCEarplugsDecibelCheck Get(string id)
		{
			return this.Get<Model.PCEarplugsDecibelCheck>(id);
		}
		
		public void Insert(Model.PCEarplugsDecibelCheck e)
		{
			this.Insert<Model.PCEarplugsDecibelCheck>(e);
		}
		
		public void Update(Model.PCEarplugsDecibelCheck e)
		{
			this.Update<Model.PCEarplugsDecibelCheck>(e);
		}
		
		public IList<Model.PCEarplugsDecibelCheck> Select()
		{
			return this.Select<Model.PCEarplugsDecibelCheck>();
		}
		
		public IList<Model.PCEarplugsDecibelCheck> Select(Helper.OrderDescription orderDescription, Helper.PagingDescription pagingDescription)
		{
			return this.Select<Model.PCEarplugsDecibelCheck>(orderDescription,pagingDescription);
		}
		public void Delete(string id)
		{
			this.Delete<Model.PCEarplugsDecibelCheck>(id);
		}
		public bool HasRows(string id)
		{
			return this.HasRows<Model.PCEarplugsDecibelCheck>(id);
		}
		public bool HasRows()
		{
			return this.HasRows<Model.PCEarplugsDecibelCheck>();
		}
		public int Count()
		{
			return this.Count<Model.PCEarplugsDecibelCheck>();
		}
		public bool HasRowsBefore(Model.PCEarplugsDecibelCheck e)
		{
			return sqlmapper.QueryForObject<bool>("PCEarplugsDecibelCheck.has_rows_before", e);
		}
		public bool HasRowsAfter(Model.PCEarplugsDecibelCheck e)
		{
			return sqlmapper.QueryForObject<bool>("PCEarplugsDecibelCheck.has_rows_after", e);
		}
		public Model.PCEarplugsDecibelCheck GetFirst()
		{
			return sqlmapper.QueryForObject<Model.PCEarplugsDecibelCheck>("PCEarplugsDecibelCheck.get_first", null);
		}
		public Model.PCEarplugsDecibelCheck GetLast()
		{
			return sqlmapper.QueryForObject<Model.PCEarplugsDecibelCheck>("PCEarplugsDecibelCheck.get_last", null);
		}
		public Model.PCEarplugsDecibelCheck GetNext(Model.PCEarplugsDecibelCheck e)
		{
			return sqlmapper.QueryForObject<Model.PCEarplugsDecibelCheck>("PCEarplugsDecibelCheck.get_next", e);
		}
		public Model.PCEarplugsDecibelCheck GetPrev(Model.PCEarplugsDecibelCheck e)
		{
			return sqlmapper.QueryForObject<Model.PCEarplugsDecibelCheck>("PCEarplugsDecibelCheck.get_prev", e);
		}
		

		public bool ExistsPrimary(string id)
		{			
			return sqlmapper.QueryForObject<bool>("PCEarplugsDecibelCheck.existsPrimary", id);
		}
    }
}
