//------------------------------------------------------------------------------
//
// 说明： 该文件中的内容是由代码生成器自动生成的，请勿手工修改！
//
// file name：PCEarplugsResilienceCheckDetailAccessor.autogenerated.cs
// author: mayanjun
// create date：2019/5/10 10:49:43
//
//------------------------------------------------------------------------------
using System;
using System.Collections;
using System.Collections.Generic;
using System.Data;
using System.Data.SqlClient;
using System.Text;

namespace Book.DA.SQLServer
{
    public partial class PCEarplugsResilienceCheckDetailAccessor
    {
		public Model.PCEarplugsResilienceCheckDetail Get(string id)
		{
			return this.Get<Model.PCEarplugsResilienceCheckDetail>(id);
		}
		
		public void Insert(Model.PCEarplugsResilienceCheckDetail e)
		{
			this.Insert<Model.PCEarplugsResilienceCheckDetail>(e);
		}
		
		public void Update(Model.PCEarplugsResilienceCheckDetail e)
		{
			this.Update<Model.PCEarplugsResilienceCheckDetail>(e);
		}
		
		public IList<Model.PCEarplugsResilienceCheckDetail> Select()
		{
			return this.Select<Model.PCEarplugsResilienceCheckDetail>();
		}
		
		public IList<Model.PCEarplugsResilienceCheckDetail> Select(Helper.OrderDescription orderDescription, Helper.PagingDescription pagingDescription)
		{
			return this.Select<Model.PCEarplugsResilienceCheckDetail>(orderDescription,pagingDescription);
		}
		public void Delete(string id)
		{
			this.Delete<Model.PCEarplugsResilienceCheckDetail>(id);
		}
		public bool HasRows(string id)
		{
			return this.HasRows<Model.PCEarplugsResilienceCheckDetail>(id);
		}
		public bool HasRows()
		{
			return this.HasRows<Model.PCEarplugsResilienceCheckDetail>();
		}
		public int Count()
		{
			return this.Count<Model.PCEarplugsResilienceCheckDetail>();
		}

		public bool ExistsPrimary(string id)
		{			
			return sqlmapper.QueryForObject<bool>("PCEarplugsResilienceCheckDetail.existsPrimary", id);
		}
    }
}
