//------------------------------------------------------------------------------
//
// 说明： 该文件中的内容是由代码生成器自动生成的，请勿手工修改！
//
// file name：PCEarplugsResilienceCheckAccessor.autogenerated.cs
// author: mayanjun
// create date：2019/5/10 10:49:43
//
//------------------------------------------------------------------------------
using System;
using System.Collections;
using System.Collections.Generic;
using System.Data;
using System.Data.SqlClient;
using System.Text;

namespace Book.DA.SQLServer
{
    public partial class PCEarplugsResilienceCheckAccessor
    {
		public Model.PCEarplugsResilienceCheck Get(string id)
		{
			return this.Get<Model.PCEarplugsResilienceCheck>(id);
		}
		
		public void Insert(Model.PCEarplugsResilienceCheck e)
		{
			this.Insert<Model.PCEarplugsResilienceCheck>(e);
		}
		
		public void Update(Model.PCEarplugsResilienceCheck e)
		{
			this.Update<Model.PCEarplugsResilienceCheck>(e);
		}
		
		public IList<Model.PCEarplugsResilienceCheck> Select()
		{
			return this.Select<Model.PCEarplugsResilienceCheck>();
		}
		
		public IList<Model.PCEarplugsResilienceCheck> Select(Helper.OrderDescription orderDescription, Helper.PagingDescription pagingDescription)
		{
			return this.Select<Model.PCEarplugsResilienceCheck>(orderDescription,pagingDescription);
		}
		public void Delete(string id)
		{
			this.Delete<Model.PCEarplugsResilienceCheck>(id);
		}
		public bool HasRows(string id)
		{
			return this.HasRows<Model.PCEarplugsResilienceCheck>(id);
		}
		public bool HasRows()
		{
			return this.HasRows<Model.PCEarplugsResilienceCheck>();
		}
		public int Count()
		{
			return this.Count<Model.PCEarplugsResilienceCheck>();
		}
		public bool HasRowsBefore(Model.PCEarplugsResilienceCheck e)
		{
			return sqlmapper.QueryForObject<bool>("PCEarplugsResilienceCheck.has_rows_before", e);
		}
		public bool HasRowsAfter(Model.PCEarplugsResilienceCheck e)
		{
			return sqlmapper.QueryForObject<bool>("PCEarplugsResilienceCheck.has_rows_after", e);
		}
		public Model.PCEarplugsResilienceCheck GetFirst()
		{
			return sqlmapper.QueryForObject<Model.PCEarplugsResilienceCheck>("PCEarplugsResilienceCheck.get_first", null);
		}
		public Model.PCEarplugsResilienceCheck GetLast()
		{
			return sqlmapper.QueryForObject<Model.PCEarplugsResilienceCheck>("PCEarplugsResilienceCheck.get_last", null);
		}
		public Model.PCEarplugsResilienceCheck GetNext(Model.PCEarplugsResilienceCheck e)
		{
			return sqlmapper.QueryForObject<Model.PCEarplugsResilienceCheck>("PCEarplugsResilienceCheck.get_next", e);
		}
		public Model.PCEarplugsResilienceCheck GetPrev(Model.PCEarplugsResilienceCheck e)
		{
			return sqlmapper.QueryForObject<Model.PCEarplugsResilienceCheck>("PCEarplugsResilienceCheck.get_prev", e);
		}
		

		public bool ExistsPrimary(string id)
		{			
			return sqlmapper.QueryForObject<bool>("PCEarplugsResilienceCheck.existsPrimary", id);
		}
    }
}
