//------------------------------------------------------------------------------
//
// 说明： 该文件中的内容是由代码生成器自动生成的，请勿手工修改！
//
// file name：PCEarplugsStayWireCheckDetailAccessor.autogenerated.cs
// author: mayanjun
// create date：2019/5/14 10:01:27
//
//------------------------------------------------------------------------------
using System;
using System.Collections;
using System.Collections.Generic;
using System.Data;
using System.Data.SqlClient;
using System.Text;

namespace Book.DA.SQLServer
{
    public partial class PCEarplugsStayWireCheckDetailAccessor
    {
		public Model.PCEarplugsStayWireCheckDetail Get(string id)
		{
			return this.Get<Model.PCEarplugsStayWireCheckDetail>(id);
		}
		
		public void Insert(Model.PCEarplugsStayWireCheckDetail e)
		{
			this.Insert<Model.PCEarplugsStayWireCheckDetail>(e);
		}
		
		public void Update(Model.PCEarplugsStayWireCheckDetail e)
		{
			this.Update<Model.PCEarplugsStayWireCheckDetail>(e);
		}
		
		public IList<Model.PCEarplugsStayWireCheckDetail> Select()
		{
			return this.Select<Model.PCEarplugsStayWireCheckDetail>();
		}
		
		public IList<Model.PCEarplugsStayWireCheckDetail> Select(Helper.OrderDescription orderDescription, Helper.PagingDescription pagingDescription)
		{
			return this.Select<Model.PCEarplugsStayWireCheckDetail>(orderDescription,pagingDescription);
		}
		public void Delete(string id)
		{
			this.Delete<Model.PCEarplugsStayWireCheckDetail>(id);
		}
		public bool HasRows(string id)
		{
			return this.HasRows<Model.PCEarplugsStayWireCheckDetail>(id);
		}
		public bool HasRows()
		{
			return this.HasRows<Model.PCEarplugsStayWireCheckDetail>();
		}
		public int Count()
		{
			return this.Count<Model.PCEarplugsStayWireCheckDetail>();
		}

		public bool ExistsPrimary(string id)
		{			
			return sqlmapper.QueryForObject<bool>("PCEarplugsStayWireCheckDetail.existsPrimary", id);
		}
    }
}
