//------------------------------------------------------------------------------
//
// 说明： 该文件中的内容是由代码生成器自动生成的，请勿手工修改！
//
// file name：PCEarplugsDecibelCheckDetailAccessor.autogenerated.cs
// author: mayanjun
// create date：2019/5/12 14:43:54
//
//------------------------------------------------------------------------------
using System;
using System.Collections;
using System.Collections.Generic;
using System.Data;
using System.Data.SqlClient;
using System.Text;

namespace Book.DA.SQLServer
{
    public partial class PCEarplugsDecibelCheckDetailAccessor
    {
		public Model.PCEarplugsDecibelCheckDetail Get(string id)
		{
			return this.Get<Model.PCEarplugsDecibelCheckDetail>(id);
		}
		
		public void Insert(Model.PCEarplugsDecibelCheckDetail e)
		{
			this.Insert<Model.PCEarplugsDecibelCheckDetail>(e);
		}
		
		public void Update(Model.PCEarplugsDecibelCheckDetail e)
		{
			this.Update<Model.PCEarplugsDecibelCheckDetail>(e);
		}
		
		public IList<Model.PCEarplugsDecibelCheckDetail> Select()
		{
			return this.Select<Model.PCEarplugsDecibelCheckDetail>();
		}
		
		public IList<Model.PCEarplugsDecibelCheckDetail> Select(Helper.OrderDescription orderDescription, Helper.PagingDescription pagingDescription)
		{
			return this.Select<Model.PCEarplugsDecibelCheckDetail>(orderDescription,pagingDescription);
		}
		public void Delete(string id)
		{
			this.Delete<Model.PCEarplugsDecibelCheckDetail>(id);
		}
		public bool HasRows(string id)
		{
			return this.HasRows<Model.PCEarplugsDecibelCheckDetail>(id);
		}
		public bool HasRows()
		{
			return this.HasRows<Model.PCEarplugsDecibelCheckDetail>();
		}
		public int Count()
		{
			return this.Count<Model.PCEarplugsDecibelCheckDetail>();
		}

		public bool ExistsPrimary(string id)
		{			
			return sqlmapper.QueryForObject<bool>("PCEarplugsDecibelCheckDetail.existsPrimary", id);
		}
    }
}
