//------------------------------------------------------------------------------
//
// 说明： 该文件中的内容是由代码生成器自动生成的，请勿手工修改！
//
// file name：PCLaserMachineAccessor.autogenerated.cs
// author: mayanjun
// create date：2015/1/18 下午 08:12:17
//
//------------------------------------------------------------------------------
using System;
using System.Collections;
using System.Collections.Generic;
using System.Data;
using System.Data.SqlClient;
using System.Text;

namespace Book.DA.SQLServer
{
    public partial class PCLaserMachineAccessor
    {
		public Model.PCLaserMachine Get(string id)
		{
			return this.Get<Model.PCLaserMachine>(id);
		}
		
		public void Insert(Model.PCLaserMachine e)
		{
			this.Insert<Model.PCLaserMachine>(e);
		}
		
		public void Update(Model.PCLaserMachine e)
		{
			this.Update<Model.PCLaserMachine>(e);
		}
		
		public IList<Model.PCLaserMachine> Select()
		{
			return this.Select<Model.PCLaserMachine>();
		}
		
		public IList<Model.PCLaserMachine> Select(Helper.OrderDescription orderDescription, Helper.PagingDescription pagingDescription)
		{
			return this.Select<Model.PCLaserMachine>(orderDescription,pagingDescription);
		}
		public void Delete(string id)
		{
			this.Delete<Model.PCLaserMachine>(id);
		}
		public bool HasRows(string id)
		{
			return this.HasRows<Model.PCLaserMachine>(id);
		}
		public bool HasRows()
		{
			return this.HasRows<Model.PCLaserMachine>();
		}
		public int Count()
		{
			return this.Count<Model.PCLaserMachine>();
		}

		public bool ExistsPrimary(string id)
		{			
			return sqlmapper.QueryForObject<bool>("PCLaserMachine.existsPrimary", id);
		}
    }
}
