//------------------------------------------------------------------------------
//
// 说明： 该文件中的内容是由代码生成器自动生成的，请勿手工修改！
//
// file name：PCOpticalMachineAccessor.autogenerated.cs
// author: mayanjun
// create date：2015/1/18 下午 08:12:17
//
//------------------------------------------------------------------------------
using System;
using System.Collections;
using System.Collections.Generic;
using System.Data;
using System.Data.SqlClient;
using System.Text;

namespace Book.DA.SQLServer
{
    public partial class PCOpticalMachineAccessor
    {
		public Model.PCOpticalMachine Get(string id)
		{
			return this.Get<Model.PCOpticalMachine>(id);
		}
		
		public void Insert(Model.PCOpticalMachine e)
		{
			this.Insert<Model.PCOpticalMachine>(e);
		}
		
		public void Update(Model.PCOpticalMachine e)
		{
			this.Update<Model.PCOpticalMachine>(e);
		}
		
		public IList<Model.PCOpticalMachine> Select()
		{
			return this.Select<Model.PCOpticalMachine>();
		}
		
		public IList<Model.PCOpticalMachine> Select(Helper.OrderDescription orderDescription, Helper.PagingDescription pagingDescription)
		{
			return this.Select<Model.PCOpticalMachine>(orderDescription,pagingDescription);
		}
		public void Delete(string id)
		{
			this.Delete<Model.PCOpticalMachine>(id);
		}
		public bool HasRows(string id)
		{
			return this.HasRows<Model.PCOpticalMachine>(id);
		}
		public bool HasRows()
		{
			return this.HasRows<Model.PCOpticalMachine>();
		}
		public int Count()
		{
			return this.Count<Model.PCOpticalMachine>();
		}

		public bool ExistsPrimary(string id)
		{			
			return sqlmapper.QueryForObject<bool>("PCOpticalMachine.existsPrimary", id);
		}
    }
}
