//------------------------------------------------------------------------------
//
// 说明： 该文件中的内容是由代码生成器自动生成的，请勿手工修改！
//
// file name：PCPerspectiveAccessor.autogenerated.cs
// author: mayanjun
// create date：2015/1/18 下午 08:12:17
//
//------------------------------------------------------------------------------
using System;
using System.Collections;
using System.Collections.Generic;
using System.Data;
using System.Data.SqlClient;
using System.Text;

namespace Book.DA.SQLServer
{
    public partial class PCPerspectiveAccessor
    {
		public Model.PCPerspective Get(string id)
		{
			return this.Get<Model.PCPerspective>(id);
		}
		
		public void Insert(Model.PCPerspective e)
		{
			this.Insert<Model.PCPerspective>(e);
		}
		
		public void Update(Model.PCPerspective e)
		{
			this.Update<Model.PCPerspective>(e);
		}
		
		public IList<Model.PCPerspective> Select()
		{
			return this.Select<Model.PCPerspective>();
		}
		
		public IList<Model.PCPerspective> Select(Helper.OrderDescription orderDescription, Helper.PagingDescription pagingDescription)
		{
			return this.Select<Model.PCPerspective>(orderDescription,pagingDescription);
		}
		public void Delete(string id)
		{
			this.Delete<Model.PCPerspective>(id);
		}
		public bool HasRows(string id)
		{
			return this.HasRows<Model.PCPerspective>(id);
		}
		public bool HasRows()
		{
			return this.HasRows<Model.PCPerspective>();
		}
		public int Count()
		{
			return this.Count<Model.PCPerspective>();
		}

		public bool ExistsPrimary(string id)
		{			
			return sqlmapper.QueryForObject<bool>("PCPerspective.existsPrimary", id);
		}
    }
}
