//------------------------------------------------------------------------------
//
// 说明：该文件中的内容是由代码生成器自动生成的，请勿手工修改！
//
// file name：BillIdDeletedManager.autogenerated.cs
// author: mayanjun
// create date：2015/11/20 18:57:00
//
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;

namespace Book.BL
{
    public partial class BillIdDeletedManager
    {
		///<summary>
		/// Data accessor of dbo.BillIdDeleted
		///</summary>
		private static readonly DA.IBillIdDeletedAccessor accessor = (DA.IBillIdDeletedAccessor)Accessors.Get("BillIdDeletedAccessor");
		
		/// <summary>
		/// Select by primary key.
		/// </summary>		
		public Model.BillIdDeleted Get(string billId)
		{
			return accessor.Get(billId);
		}
		
		public bool HasRows(string billId)
		{
			return accessor.HasRows(billId);
		}
		
		public bool HasRows()
		{
			return accessor.HasRows();
		}
		
		
		/// <summary>
		/// Select all.
		/// </summary>
		public IList<Model.BillIdDeleted> Select()
		{
			return accessor.Select();
		}
		
		/// <summary>
		/// 获取记录总数
		/// </summary>
		public int Count()
		{
			return accessor.Count();
		}
		
		/// <summary>
		/// 获取指定状态、指定分页，并按指定要求排序的记录
		/// </summary>
		public IList<Model.BillIdDeleted> Select(Helper.OrderDescription orderDescription, Helper.PagingDescription pagingDescription)
		{
			return accessor.Select(orderDescription, pagingDescription);
		}
		public bool ExistsPrimary(string id)
		{
		    return accessor.ExistsPrimary(id);	
	    }
		
    }
}
