//------------------------------------------------------------------------------
//
// 说明：该文件中的内容是由代码生成器自动生成的，请勿手工修改！
//
// file name：JISDataInputManager.autogenerated.cs
// author: mayanjun
// create date：2018-07-23 20:14:21
//
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;

namespace Book.BL
{
    public partial class JISDataInputManager
    {
		///<summary>
		/// Data accessor of dbo.JISDataInput
		///</summary>
		private static readonly DA.IJISDataInputAccessor accessor = (DA.IJISDataInputAccessor)Accessors.Get("JISDataInputAccessor");
		
		/// <summary>
		/// Select by primary key.
		/// </summary>		
		public Model.JISDataInput Get(string jISDataInputId)
		{
			return accessor.Get(jISDataInputId);
		}
		
		public bool HasRows(string jISDataInputId)
		{
			return accessor.HasRows(jISDataInputId);
		}
		
		public bool HasRows()
		{
			return accessor.HasRows();
		}
		
		
		public bool HasRowsBefore(Model.JISDataInput e)
		{
			return accessor.HasRowsBefore(e);
		}
		
		public bool HasRowsAfter(Model.JISDataInput e)
		{
			return accessor.HasRowsAfter(e);
		}
		
		public Model.JISDataInput GetFirst()
		{
			return accessor.GetFirst();
		}
		
		public Model.JISDataInput GetLast()
		{
			return accessor.GetLast();
		}
		
		public Model.JISDataInput GetPrev(Model.JISDataInput e)
		{
			return accessor.GetPrev(e);
		}
		
		public Model.JISDataInput GetNext(Model.JISDataInput e)
		{
			return accessor.GetNext(e);
		}
		/// <summary>
		/// Select all.
		/// </summary>
		public IList<Model.JISDataInput> Select()
		{
			return accessor.Select();
		}
		
		/// <summary>
		/// 获取记录总数
		/// </summary>
		public int Count()
		{
			return accessor.Count();
		}
		
		/// <summary>
		/// 获取指定状态、指定分页，并按指定要求排序的记录
		/// </summary>
		public IList<Model.JISDataInput> Select(Helper.OrderDescription orderDescription, Helper.PagingDescription pagingDescription)
		{
			return accessor.Select(orderDescription, pagingDescription);
		}
		public bool ExistsPrimary(string id)
		{
		    return accessor.ExistsPrimary(id);	
	    }
		
    }
}
