//------------------------------------------------------------------------------
//
// 说明：该文件中的内容是由代码生成器自动生成的，请勿手工修改！
//
// file name：PCAssemblyInspectionDetailManager.autogenerated.cs
// author: mayanjun
// create date：2017-11-05 16:28:12
//
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;

namespace Book.BL
{
    public partial class PCAssemblyInspectionDetailManager
    {
		///<summary>
		/// Data accessor of dbo.PCAssemblyInspectionDetail
		///</summary>
		private static readonly DA.IPCAssemblyInspectionDetailAccessor accessor = (DA.IPCAssemblyInspectionDetailAccessor)Accessors.Get("PCAssemblyInspectionDetailAccessor");
		
		/// <summary>
		/// Select by primary key.
		/// </summary>		
		public Model.PCAssemblyInspectionDetail Get(string pCAssemblyInspectionDetailId)
		{
			return accessor.Get(pCAssemblyInspectionDetailId);
		}
		
		public bool HasRows(string pCAssemblyInspectionDetailId)
		{
			return accessor.HasRows(pCAssemblyInspectionDetailId);
		}
		
		public bool HasRows()
		{
			return accessor.HasRows();
		}
		
		
		/// <summary>
		/// Select all.
		/// </summary>
		public IList<Model.PCAssemblyInspectionDetail> Select()
		{
			return accessor.Select();
		}
		
		/// <summary>
		/// 获取记录总数
		/// </summary>
		public int Count()
		{
			return accessor.Count();
		}
		
		/// <summary>
		/// 获取指定状态、指定分页，并按指定要求排序的记录
		/// </summary>
		public IList<Model.PCAssemblyInspectionDetail> Select(Helper.OrderDescription orderDescription, Helper.PagingDescription pagingDescription)
		{
			return accessor.Select(orderDescription, pagingDescription);
		}
		public bool ExistsPrimary(string id)
		{
		    return accessor.ExistsPrimary(id);	
	    }
		
    }
}
