//------------------------------------------------------------------------------
//
// 说明：该文件中的内容是由代码生成器自动生成的，请勿手工修改！
//
// file name：PCAssemblyInspectionManager.autogenerated.cs
// author: mayanjun
// create date：2017-11-05 16:28:12
//
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;

namespace Book.BL
{
    public partial class PCAssemblyInspectionManager
    {
		///<summary>
		/// Data accessor of dbo.PCAssemblyInspection
		///</summary>
		private static readonly DA.IPCAssemblyInspectionAccessor accessor = (DA.IPCAssemblyInspectionAccessor)Accessors.Get("PCAssemblyInspectionAccessor");
		
		/// <summary>
		/// Select by primary key.
		/// </summary>		
		public Model.PCAssemblyInspection Get(string pCAssemblyInspectionId)
		{
			return accessor.Get(pCAssemblyInspectionId);
		}
		
		public bool HasRows(string pCAssemblyInspectionId)
		{
			return accessor.HasRows(pCAssemblyInspectionId);
		}
		
		public bool HasRows()
		{
			return accessor.HasRows();
		}
		
		
		public bool HasRowsBefore(Model.PCAssemblyInspection e)
		{
			return accessor.HasRowsBefore(e);
		}
		
		public bool HasRowsAfter(Model.PCAssemblyInspection e)
		{
			return accessor.HasRowsAfter(e);
		}
		
		public Model.PCAssemblyInspection GetFirst()
		{
			return accessor.GetFirst();
		}
		
		public Model.PCAssemblyInspection GetLast()
		{
			return accessor.GetLast();
		}
		
		public Model.PCAssemblyInspection GetPrev(Model.PCAssemblyInspection e)
		{
			return accessor.GetPrev(e);
		}
		
		public Model.PCAssemblyInspection GetNext(Model.PCAssemblyInspection e)
		{
			return accessor.GetNext(e);
		}
		/// <summary>
		/// Select all.
		/// </summary>
		public IList<Model.PCAssemblyInspection> Select()
		{
			return accessor.Select();
		}
		
		/// <summary>
		/// 获取记录总数
		/// </summary>
		public int Count()
		{
			return accessor.Count();
		}
		
		/// <summary>
		/// 获取指定状态、指定分页，并按指定要求排序的记录
		/// </summary>
		public IList<Model.PCAssemblyInspection> Select(Helper.OrderDescription orderDescription, Helper.PagingDescription pagingDescription)
		{
			return accessor.Select(orderDescription, pagingDescription);
		}
		public bool ExistsPrimary(string id)
		{
		    return accessor.ExistsPrimary(id);	
	    }
		
    }
}
