//------------------------------------------------------------------------------
//
// 说明：该文件中的内容是由代码生成器自动生成的，请勿手工修改！
//
// file name：PCDataInputManager.autogenerated.cs
// author: mayanjun
// create date：2015/1/18 下午 08:12:16
//
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;

namespace Book.BL
{
    public partial class PCDataInputManager
    {
		///<summary>
		/// Data accessor of dbo.PCDataInput
		///</summary>
		private static readonly DA.IPCDataInputAccessor accessor = (DA.IPCDataInputAccessor)Accessors.Get("PCDataInputAccessor");
		
		/// <summary>
		/// Select by primary key.
		/// </summary>		
		public Model.PCDataInput Get(string pCDataInputId)
		{
			return accessor.Get(pCDataInputId);
		}
		
		public bool HasRows(string pCDataInputId)
		{
			return accessor.HasRows(pCDataInputId);
		}
		
		public bool HasRows()
		{
			return accessor.HasRows();
		}
		
		
		public bool HasRowsBefore(Model.PCDataInput e)
		{
			return accessor.HasRowsBefore(e);
		}
		
		public bool HasRowsAfter(Model.PCDataInput e)
		{
			return accessor.HasRowsAfter(e);
		}
		
		public Model.PCDataInput GetFirst()
		{
			return accessor.GetFirst();
		}
		
		public Model.PCDataInput GetLast()
		{
			return accessor.GetLast();
		}
		
		public Model.PCDataInput GetPrev(Model.PCDataInput e)
		{
			return accessor.GetPrev(e);
		}
		
		public Model.PCDataInput GetNext(Model.PCDataInput e)
		{
			return accessor.GetNext(e);
		}
		/// <summary>
		/// Select all.
		/// </summary>
		public IList<Model.PCDataInput> Select()
		{
			return accessor.Select();
		}
		
		/// <summary>
		/// 获取记录总数
		/// </summary>
		public int Count()
		{
			return accessor.Count();
		}
		
		/// <summary>
		/// 获取指定状态、指定分页，并按指定要求排序的记录
		/// </summary>
		public IList<Model.PCDataInput> Select(Helper.OrderDescription orderDescription, Helper.PagingDescription pagingDescription)
		{
			return accessor.Select(orderDescription, pagingDescription);
		}
		public bool ExistsPrimary(string id)
		{
		    return accessor.ExistsPrimary(id);	
	    }
		
    }
}
