//------------------------------------------------------------------------------
//
// 说明：该文件中的内容是由代码生成器自动生成的，请勿手工修改！
//
// file name：PCEarplugsResilienceConditionSetManager.autogenerated.cs
// author: mayanjun
// create date：2019/6/15 19:29:48
//
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;

namespace Book.BL
{
    public partial class PCEarplugsResilienceConditionSetManager
    {
		///<summary>
		/// Data accessor of dbo.PCEarplugsResilienceConditionSet
		///</summary>
		private static readonly DA.IPCEarplugsResilienceConditionSetAccessor accessor = (DA.IPCEarplugsResilienceConditionSetAccessor)Accessors.Get("PCEarplugsResilienceConditionSetAccessor");
		
		/// <summary>
		/// Select by primary key.
		/// </summary>		
		public Model.PCEarplugsResilienceConditionSet Get(string pCEarplugsResilienceConditionSetId)
		{
			return accessor.Get(pCEarplugsResilienceConditionSetId);
		}
		
		public bool HasRows(string pCEarplugsResilienceConditionSetId)
		{
			return accessor.HasRows(pCEarplugsResilienceConditionSetId);
		}
		
		public bool HasRows()
		{
			return accessor.HasRows();
		}
		
		
		public bool HasRowsBefore(Model.PCEarplugsResilienceConditionSet e)
		{
			return accessor.HasRowsBefore(e);
		}
		
		public bool HasRowsAfter(Model.PCEarplugsResilienceConditionSet e)
		{
			return accessor.HasRowsAfter(e);
		}
		
		public Model.PCEarplugsResilienceConditionSet GetFirst()
		{
			return accessor.GetFirst();
		}
		
		public Model.PCEarplugsResilienceConditionSet GetLast()
		{
			return accessor.GetLast();
		}
		
		public Model.PCEarplugsResilienceConditionSet GetPrev(Model.PCEarplugsResilienceConditionSet e)
		{
			return accessor.GetPrev(e);
		}
		
		public Model.PCEarplugsResilienceConditionSet GetNext(Model.PCEarplugsResilienceConditionSet e)
		{
			return accessor.GetNext(e);
		}
		/// <summary>
		/// Select all.
		/// </summary>
		public IList<Model.PCEarplugsResilienceConditionSet> Select()
		{
			return accessor.Select();
		}
		
		/// <summary>
		/// 获取记录总数
		/// </summary>
		public int Count()
		{
			return accessor.Count();
		}
		
		/// <summary>
		/// 获取指定状态、指定分页，并按指定要求排序的记录
		/// </summary>
		public IList<Model.PCEarplugsResilienceConditionSet> Select(Helper.OrderDescription orderDescription, Helper.PagingDescription pagingDescription)
		{
			return accessor.Select(orderDescription, pagingDescription);
		}
		public bool ExistsPrimary(string id)
		{
		    return accessor.ExistsPrimary(id);	
	    }
		
    }
}
