//------------------------------------------------------------------------------
//
// 说明：该文件中的内容是由代码生成器自动生成的，请勿手工修改！
//
// file name：PCEarplugsResilienceCheckDetailManager.autogenerated.cs
// author: mayanjun
// create date：2019/5/10 10:49:43
//
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;

namespace Book.BL
{
    public partial class PCEarplugsResilienceCheckDetailManager
    {
		///<summary>
		/// Data accessor of dbo.PCEarplugsResilienceCheckDetail
		///</summary>
		private static readonly DA.IPCEarplugsResilienceCheckDetailAccessor accessor = (DA.IPCEarplugsResilienceCheckDetailAccessor)Accessors.Get("PCEarplugsResilienceCheckDetailAccessor");
		
		/// <summary>
		/// Select by primary key.
		/// </summary>		
		public Model.PCEarplugsResilienceCheckDetail Get(string pCEarplugsResilienceCheckDetailId)
		{
			return accessor.Get(pCEarplugsResilienceCheckDetailId);
		}
		
		public bool HasRows(string pCEarplugsResilienceCheckDetailId)
		{
			return accessor.HasRows(pCEarplugsResilienceCheckDetailId);
		}
		
		public bool HasRows()
		{
			return accessor.HasRows();
		}
		
		
		/// <summary>
		/// Select all.
		/// </summary>
		public IList<Model.PCEarplugsResilienceCheckDetail> Select()
		{
			return accessor.Select();
		}
		
		/// <summary>
		/// 获取记录总数
		/// </summary>
		public int Count()
		{
			return accessor.Count();
		}
		
		/// <summary>
		/// 获取指定状态、指定分页，并按指定要求排序的记录
		/// </summary>
		public IList<Model.PCEarplugsResilienceCheckDetail> Select(Helper.OrderDescription orderDescription, Helper.PagingDescription pagingDescription)
		{
			return accessor.Select(orderDescription, pagingDescription);
		}
		public bool ExistsPrimary(string id)
		{
		    return accessor.ExistsPrimary(id);	
	    }
		
    }
}
