//------------------------------------------------------------------------------
//
// 说明：该文件中的内容是由代码生成器自动生成的，请勿手工修改！
//
// file name：PCEarplugsStayWireCheckManager.autogenerated.cs
// author: mayanjun
// create date：2019/5/14 09:57:06
//
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;

namespace Book.BL
{
    public partial class PCEarplugsStayWireCheckManager
    {
		///<summary>
		/// Data accessor of dbo.PCEarplugsStayWireCheck
		///</summary>
		private static readonly DA.IPCEarplugsStayWireCheckAccessor accessor = (DA.IPCEarplugsStayWireCheckAccessor)Accessors.Get("PCEarplugsStayWireCheckAccessor");
		
		/// <summary>
		/// Select by primary key.
		/// </summary>		
		public Model.PCEarplugsStayWireCheck Get(string pCEarplugsStayWireCheckId)
		{
			return accessor.Get(pCEarplugsStayWireCheckId);
		}
		
		public bool HasRows(string pCEarplugsStayWireCheckId)
		{
			return accessor.HasRows(pCEarplugsStayWireCheckId);
		}
		
		public bool HasRows()
		{
			return accessor.HasRows();
		}
		
		
		public bool HasRowsBefore(Model.PCEarplugsStayWireCheck e)
		{
			return accessor.HasRowsBefore(e);
		}
		
		public bool HasRowsAfter(Model.PCEarplugsStayWireCheck e)
		{
			return accessor.HasRowsAfter(e);
		}
		
		public Model.PCEarplugsStayWireCheck GetFirst()
		{
			return accessor.GetFirst();
		}
		
		public Model.PCEarplugsStayWireCheck GetLast()
		{
			return accessor.GetLast();
		}
		
		public Model.PCEarplugsStayWireCheck GetPrev(Model.PCEarplugsStayWireCheck e)
		{
			return accessor.GetPrev(e);
		}
		
		public Model.PCEarplugsStayWireCheck GetNext(Model.PCEarplugsStayWireCheck e)
		{
			return accessor.GetNext(e);
		}
		/// <summary>
		/// Select all.
		/// </summary>
		public IList<Model.PCEarplugsStayWireCheck> Select()
		{
			return accessor.Select();
		}
		
		/// <summary>
		/// 获取记录总数
		/// </summary>
		public int Count()
		{
			return accessor.Count();
		}
		
		/// <summary>
		/// 获取指定状态、指定分页，并按指定要求排序的记录
		/// </summary>
		public IList<Model.PCEarplugsStayWireCheck> Select(Helper.OrderDescription orderDescription, Helper.PagingDescription pagingDescription)
		{
			return accessor.Select(orderDescription, pagingDescription);
		}
		public bool ExistsPrimary(string id)
		{
		    return accessor.ExistsPrimary(id);	
	    }
		
    }
}
