//------------------------------------------------------------------------------
//
// 说明：该文件中的内容是由代码生成器自动生成的，请勿手工修改！
//
// file name：PCEarplugsResilienceCheckManager.autogenerated.cs
// author: mayanjun
// create date：2019/5/10 10:49:43
//
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;

namespace Book.BL
{
    public partial class PCEarplugsResilienceCheckManager
    {
		///<summary>
		/// Data accessor of dbo.PCEarplugsResilienceCheck
		///</summary>
		private static readonly DA.IPCEarplugsResilienceCheckAccessor accessor = (DA.IPCEarplugsResilienceCheckAccessor)Accessors.Get("PCEarplugsResilienceCheckAccessor");
		
		/// <summary>
		/// Select by primary key.
		/// </summary>		
		public Model.PCEarplugsResilienceCheck Get(string pCEarplugsResilienceCheckId)
		{
			return accessor.Get(pCEarplugsResilienceCheckId);
		}
		
		public bool HasRows(string pCEarplugsResilienceCheckId)
		{
			return accessor.HasRows(pCEarplugsResilienceCheckId);
		}
		
		public bool HasRows()
		{
			return accessor.HasRows();
		}
		
		
		public bool HasRowsBefore(Model.PCEarplugsResilienceCheck e)
		{
			return accessor.HasRowsBefore(e);
		}
		
		public bool HasRowsAfter(Model.PCEarplugsResilienceCheck e)
		{
			return accessor.HasRowsAfter(e);
		}
		
		public Model.PCEarplugsResilienceCheck GetFirst()
		{
			return accessor.GetFirst();
		}
		
		public Model.PCEarplugsResilienceCheck GetLast()
		{
			return accessor.GetLast();
		}
		
		public Model.PCEarplugsResilienceCheck GetPrev(Model.PCEarplugsResilienceCheck e)
		{
			return accessor.GetPrev(e);
		}
		
		public Model.PCEarplugsResilienceCheck GetNext(Model.PCEarplugsResilienceCheck e)
		{
			return accessor.GetNext(e);
		}
		/// <summary>
		/// Select all.
		/// </summary>
		public IList<Model.PCEarplugsResilienceCheck> Select()
		{
			return accessor.Select();
		}
		
		/// <summary>
		/// 获取记录总数
		/// </summary>
		public int Count()
		{
			return accessor.Count();
		}
		
		/// <summary>
		/// 获取指定状态、指定分页，并按指定要求排序的记录
		/// </summary>
		public IList<Model.PCEarplugsResilienceCheck> Select(Helper.OrderDescription orderDescription, Helper.PagingDescription pagingDescription)
		{
			return accessor.Select(orderDescription, pagingDescription);
		}
		public bool ExistsPrimary(string id)
		{
		    return accessor.ExistsPrimary(id);	
	    }
		
    }
}
