//------------------------------------------------------------------------------
//
// 说明：该文件中的内容是由代码生成器自动生成的，请勿手工修改！
//
// file name：PCEarplugsDecibelCheckDetailManager.autogenerated.cs
// author: mayanjun
// create date：2019/5/12 14:43:54
//
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;

namespace Book.BL
{
    public partial class PCEarplugsDecibelCheckDetailManager
    {
		///<summary>
		/// Data accessor of dbo.PCEarplugsDecibelCheckDetail
		///</summary>
		private static readonly DA.IPCEarplugsDecibelCheckDetailAccessor accessor = (DA.IPCEarplugsDecibelCheckDetailAccessor)Accessors.Get("PCEarplugsDecibelCheckDetailAccessor");
		
		/// <summary>
		/// Select by primary key.
		/// </summary>		
		public Model.PCEarplugsDecibelCheckDetail Get(string pCEarplugsDecibelCheckDetailId)
		{
			return accessor.Get(pCEarplugsDecibelCheckDetailId);
		}
		
		public bool HasRows(string pCEarplugsDecibelCheckDetailId)
		{
			return accessor.HasRows(pCEarplugsDecibelCheckDetailId);
		}
		
		public bool HasRows()
		{
			return accessor.HasRows();
		}
		
		
		/// <summary>
		/// Select all.
		/// </summary>
		public IList<Model.PCEarplugsDecibelCheckDetail> Select()
		{
			return accessor.Select();
		}
		
		/// <summary>
		/// 获取记录总数
		/// </summary>
		public int Count()
		{
			return accessor.Count();
		}
		
		/// <summary>
		/// 获取指定状态、指定分页，并按指定要求排序的记录
		/// </summary>
		public IList<Model.PCEarplugsDecibelCheckDetail> Select(Helper.OrderDescription orderDescription, Helper.PagingDescription pagingDescription)
		{
			return accessor.Select(orderDescription, pagingDescription);
		}
		public bool ExistsPrimary(string id)
		{
		    return accessor.ExistsPrimary(id);	
	    }
		
    }
}
