//------------------------------------------------------------------------------
//
// 说明：该文件中的内容是由代码生成器自动生成的，请勿手工修改！
//
// file name：PCEarplugsStayWireCheckDetailManager.autogenerated.cs
// author: mayanjun
// create date：2019/5/14 10:01:26
//
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;

namespace Book.BL
{
    public partial class PCEarplugsStayWireCheckDetailManager
    {
		///<summary>
		/// Data accessor of dbo.PCEarplugsStayWireCheckDetail
		///</summary>
		private static readonly DA.IPCEarplugsStayWireCheckDetailAccessor accessor = (DA.IPCEarplugsStayWireCheckDetailAccessor)Accessors.Get("PCEarplugsStayWireCheckDetailAccessor");
		
		/// <summary>
		/// Select by primary key.
		/// </summary>		
		public Model.PCEarplugsStayWireCheckDetail Get(string pCEarplugsStayWireCheckDetailId)
		{
			return accessor.Get(pCEarplugsStayWireCheckDetailId);
		}
		
		public bool HasRows(string pCEarplugsStayWireCheckDetailId)
		{
			return accessor.HasRows(pCEarplugsStayWireCheckDetailId);
		}
		
		public bool HasRows()
		{
			return accessor.HasRows();
		}
		
		
		/// <summary>
		/// Select all.
		/// </summary>
		public IList<Model.PCEarplugsStayWireCheckDetail> Select()
		{
			return accessor.Select();
		}
		
		/// <summary>
		/// 获取记录总数
		/// </summary>
		public int Count()
		{
			return accessor.Count();
		}
		
		/// <summary>
		/// 获取指定状态、指定分页，并按指定要求排序的记录
		/// </summary>
		public IList<Model.PCEarplugsStayWireCheckDetail> Select(Helper.OrderDescription orderDescription, Helper.PagingDescription pagingDescription)
		{
			return accessor.Select(orderDescription, pagingDescription);
		}
		public bool ExistsPrimary(string id)
		{
		    return accessor.ExistsPrimary(id);	
	    }
		
    }
}
