//------------------------------------------------------------------------------
//
// 说明：该文件中的内容是由代码生成器自动生成的，请勿手工修改！
//
// file name：PCEarplugsDecibelCheckManager.autogenerated.cs
// author: mayanjun
// create date：2019/5/12 14:43:54
//
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;

namespace Book.BL
{
    public partial class PCEarplugsDecibelCheckManager
    {
		///<summary>
		/// Data accessor of dbo.PCEarplugsDecibelCheck
		///</summary>
		private static readonly DA.IPCEarplugsDecibelCheckAccessor accessor = (DA.IPCEarplugsDecibelCheckAccessor)Accessors.Get("PCEarplugsDecibelCheckAccessor");
		
		/// <summary>
		/// Select by primary key.
		/// </summary>		
		public Model.PCEarplugsDecibelCheck Get(string pCEarplugsDecibelCheckId)
		{
			return accessor.Get(pCEarplugsDecibelCheckId);
		}
		
		public bool HasRows(string pCEarplugsDecibelCheckId)
		{
			return accessor.HasRows(pCEarplugsDecibelCheckId);
		}
		
		public bool HasRows()
		{
			return accessor.HasRows();
		}
		
		
		public bool HasRowsBefore(Model.PCEarplugsDecibelCheck e)
		{
			return accessor.HasRowsBefore(e);
		}
		
		public bool HasRowsAfter(Model.PCEarplugsDecibelCheck e)
		{
			return accessor.HasRowsAfter(e);
		}
		
		public Model.PCEarplugsDecibelCheck GetFirst()
		{
			return accessor.GetFirst();
		}
		
		public Model.PCEarplugsDecibelCheck GetLast()
		{
			return accessor.GetLast();
		}
		
		public Model.PCEarplugsDecibelCheck GetPrev(Model.PCEarplugsDecibelCheck e)
		{
			return accessor.GetPrev(e);
		}
		
		public Model.PCEarplugsDecibelCheck GetNext(Model.PCEarplugsDecibelCheck e)
		{
			return accessor.GetNext(e);
		}
		/// <summary>
		/// Select all.
		/// </summary>
		public IList<Model.PCEarplugsDecibelCheck> Select()
		{
			return accessor.Select();
		}
		
		/// <summary>
		/// 获取记录总数
		/// </summary>
		public int Count()
		{
			return accessor.Count();
		}
		
		/// <summary>
		/// 获取指定状态、指定分页，并按指定要求排序的记录
		/// </summary>
		public IList<Model.PCEarplugsDecibelCheck> Select(Helper.OrderDescription orderDescription, Helper.PagingDescription pagingDescription)
		{
			return accessor.Select(orderDescription, pagingDescription);
		}
		public bool ExistsPrimary(string id)
		{
		    return accessor.ExistsPrimary(id);	
	    }
		
    }
}
