//------------------------------------------------------------------------------
//
// 说明：该文件中的内容是由代码生成器自动生成的，请勿手工修改！
//
// file name：PCEuropeOpticalManager.autogenerated.cs
// author: mayanjun
// create date：2015/1/18 下午 08:12:16
//
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;

namespace Book.BL
{
    public partial class PCEuropeOpticalManager
    {
		///<summary>
		/// Data accessor of dbo.PCEuropeOptical
		///</summary>
		private static readonly DA.IPCEuropeOpticalAccessor accessor = (DA.IPCEuropeOpticalAccessor)Accessors.Get("PCEuropeOpticalAccessor");
		
		/// <summary>
		/// Select by primary key.
		/// </summary>		
		public Model.PCEuropeOptical Get(string pCEuropeOpticalId)
		{
			return accessor.Get(pCEuropeOpticalId);
		}
		
		public bool HasRows(string pCEuropeOpticalId)
		{
			return accessor.HasRows(pCEuropeOpticalId);
		}
		
		public bool HasRows()
		{
			return accessor.HasRows();
		}
		
		
		/// <summary>
		/// Select all.
		/// </summary>
		public IList<Model.PCEuropeOptical> Select()
		{
			return accessor.Select();
		}
		
		/// <summary>
		/// 获取记录总数
		/// </summary>
		public int Count()
		{
			return accessor.Count();
		}
		
		/// <summary>
		/// 获取指定状态、指定分页，并按指定要求排序的记录
		/// </summary>
		public IList<Model.PCEuropeOptical> Select(Helper.OrderDescription orderDescription, Helper.PagingDescription pagingDescription)
		{
			return accessor.Select(orderDescription, pagingDescription);
		}
		public bool ExistsPrimary(string id)
		{
		    return accessor.ExistsPrimary(id);	
	    }
		
    }
}
