//------------------------------------------------------------------------------
//
// 说明： 该文件中的内容是由代码生成器自动生成的，请勿手工修改！
//
// file name：BillIdSet.autogenerated.cs
// author: mayanjun
// create date：2015/11/20 18:57:01
//
//------------------------------------------------------------------------------
using System;
namespace Book.Model
{
	public partial class BillIdSet
	{
		#region Data

		/// <summary>
		/// 
		/// </summary>
		private string _billIdSetId;
		
		/// <summary>
		/// 
		/// </summary>
		private string _englishId;
		
		/// <summary>
		/// 
		/// </summary>
		private string _startBillId;
		
		/// <summary>
		/// 
		/// </summary>
		private string _endBillId;
		
		/// <summary>
		/// 
		/// </summary>
		private DateTime? _startDate;
		
		/// <summary>
		/// 
		/// </summary>
		private DateTime? _endDate;
		
		/// <summary>
		/// 
		/// </summary>
		private DateTime? _insertTime;
		
		/// <summary>
		/// 
		/// </summary>
		private DateTime? _updatetTime;
		
		/// <summary>
		/// 
		/// </summary>
		private bool? _idState;
		
		/// <summary>
		/// 
		/// </summary>
		private int? _idNumber;
		
		 
		#endregion
		
		#region Properties
		
		/// <summary>
		/// 
		/// </summary>
		public string BillIdSetId
		{
			get 
			{
				return this._billIdSetId;
			}
			set 
			{
				this._billIdSetId = value;
			}
		}

		/// <summary>
		/// 
		/// </summary>
		public string EnglishId
		{
			get 
			{
				return this._englishId;
			}
			set 
			{
				this._englishId = value;
			}
		}

		/// <summary>
		/// 
		/// </summary>
		public string StartBillId
		{
			get 
			{
				return this._startBillId;
			}
			set 
			{
				this._startBillId = value;
			}
		}

		/// <summary>
		/// 
		/// </summary>
		public string EndBillId
		{
			get 
			{
				return this._endBillId;
			}
			set 
			{
				this._endBillId = value;
			}
		}

		/// <summary>
		/// 
		/// </summary>
		public DateTime? StartDate
		{
			get 
			{
				return this._startDate;
			}
			set 
			{
				this._startDate = value;
			}
		}

		/// <summary>
		/// 
		/// </summary>
		public DateTime? EndDate
		{
			get 
			{
				return this._endDate;
			}
			set 
			{
				this._endDate = value;
			}
		}

		/// <summary>
		/// 
		/// </summary>
		public DateTime? InsertTime
		{
			get 
			{
				return this._insertTime;
			}
			set 
			{
				this._insertTime = value;
			}
		}

		/// <summary>
		/// 
		/// </summary>
		public DateTime? UpdatetTime
		{
			get 
			{
				return this._updatetTime;
			}
			set 
			{
				this._updatetTime = value;
			}
		}

		/// <summary>
		/// 
		/// </summary>
		public bool? IdState
		{
			get 
			{
				return this._idState;
			}
			set 
			{
				this._idState = value;
			}
		}

		/// <summary>
		/// 
		/// </summary>
		public int? IdNumber
		{
			get 
			{
				return this._idNumber;
			}
			set 
			{
				this._idNumber = value;
			}
		}
	
		/// <summary>
		/// 
		/// </summary>
		public readonly static string PRO_BillIdSetId = "BillIdSetId";
		
		/// <summary>
		/// 
		/// </summary>
		public readonly static string PRO_EnglishId = "EnglishId";
		
		/// <summary>
		/// 
		/// </summary>
		public readonly static string PRO_StartBillId = "StartBillId";
		
		/// <summary>
		/// 
		/// </summary>
		public readonly static string PRO_EndBillId = "EndBillId";
		
		/// <summary>
		/// 
		/// </summary>
		public readonly static string PRO_StartDate = "StartDate";
		
		/// <summary>
		/// 
		/// </summary>
		public readonly static string PRO_EndDate = "EndDate";
		
		/// <summary>
		/// 
		/// </summary>
		public readonly static string PRO_InsertTime = "InsertTime";
		
		/// <summary>
		/// 
		/// </summary>
		public readonly static string PRO_UpdatetTime = "UpdatetTime";
		
		/// <summary>
		/// 
		/// </summary>
		public readonly static string PRO_IdState = "IdState";
		
		/// <summary>
		/// 
		/// </summary>
		public readonly static string PRO_IdNumber = "IdNumber";
		

		#endregion
	}
}