//------------------------------------------------------------------------------
//
// 说明： 该文件中的内容是由代码生成器自动生成的，请勿手工修改！
//
// file name：InformationState.autogenerated.cs
// author: mayanjun
// create date：2015/8/20 16:32:58
//
//------------------------------------------------------------------------------
using System;
namespace Book.Model
{
	public partial class InformationState
	{
		#region Data

		/// <summary>
		/// 
		/// </summary>
		private string _informationStateId;
		
		/// <summary>
		/// 
		/// </summary>
		private DateTime? _informationStateDate;
		
		/// <summary>
		/// 
		/// </summary>
		private string _employeeId;
		
		/// <summary>
		/// 
		/// </summary>
		private string _informationId;
		
		/// <summary>
		/// 
		/// </summary>
		private bool? _informationState;
		
		 
		#endregion
		
		#region Properties
		
		/// <summary>
		/// 
		/// </summary>
		public string InformationStateId
		{
			get 
			{
				return this._informationStateId;
			}
			set 
			{
				this._informationStateId = value;
			}
		}

		/// <summary>
		/// 
		/// </summary>
		public DateTime? InformationStateDate
		{
			get 
			{
				return this._informationStateDate;
			}
			set 
			{
				this._informationStateDate = value;
			}
		}

		/// <summary>
		/// 
		/// </summary>
		public string EmployeeId
		{
			get 
			{
				return this._employeeId;
			}
			set 
			{
				this._employeeId = value;
			}
		}

		/// <summary>
		/// 
		/// </summary>
		public string InformationId
		{
			get 
			{
				return this._informationId;
			}
			set 
			{
				this._informationId = value;
			}
		}

		/// <summary>
		/// 
		/// </summary>
		public bool? InformationState
		{
			get 
			{
				return this._informationState;
			}
			set 
			{
				this._informationState = value;
			}
		}
	
		/// <summary>
		/// 
		/// </summary>
		public readonly static string PRO_InformationStateId = "InformationStateId";
		
		/// <summary>
		/// 
		/// </summary>
		public readonly static string PRO_InformationStateDate = "InformationStateDate";
		
		/// <summary>
		/// 
		/// </summary>
		public readonly static string PRO_EmployeeId = "EmployeeId";
		
		/// <summary>
		/// 
		/// </summary>
		public readonly static string PRO_InformationId = "InformationId";
		
		/// <summary>
		/// 
		/// </summary>
		public readonly static string PRO_InformationState = "InformationState";
		

		#endregion
	}
}