//------------------------------------------------------------------------------
//
// 说明： 该文件中的内容是由代码生成器自动生成的，请勿手工修改！
//
// file name：JISDataInput.autogenerated.cs
// author: mayanjun
// create date：2018-07-23 20:14:22
//
//------------------------------------------------------------------------------
using System;
namespace Book.Model
{
	public partial class JISDataInput
	{
		#region Data

		/// <summary>
		/// 
		/// </summary>
		private string _jISDataInputId;
		
		/// <summary>
		/// 
		/// </summary>
		private DateTime? _jISDataInputDate;
		
		/// <summary>
		/// 
		/// </summary>
		private string _invoiceXOId;
		
		/// <summary>
		/// 
		/// </summary>
		private string _productId;
		
		/// <summary>
		/// 
		/// </summary>
		private DateTime? _insertTime;
		
		/// <summary>
		/// 
		/// </summary>
		private DateTime? _updateTime;
		
		/// <summary>
		/// 
		/// </summary>
		private double? _invoiceQuantiy;
		
		/// <summary>
		/// 
		/// </summary>
		private double? _testQuantity;
		
		/// <summary>
		/// 
		/// </summary>
		private string _color;
		
		/// <summary>
		/// 
		/// </summary>
		private string _effect;
		
		/// <summary>
		/// 
		/// </summary>
		private string _employeeId1;
		
		/// <summary>
		/// 
		/// </summary>
		private string _employeeId2;
		
		/// <summary>
		/// 
		/// </summary>
		private bool? _waiguan1;
		
		/// <summary>
		/// 
		/// </summary>
		private bool? _lingjingdu;
		
		/// <summary>
		/// 
		/// </summary>
		private bool? _quguangdu;
		
		/// <summary>
		/// 
		/// </summary>
		private bool? _sanguangdu;
		
		/// <summary>
		/// 
		/// </summary>
		private bool? _toushilv;
		
		/// <summary>
		/// 
		/// </summary>
		private bool? _chongji1;
		
		/// <summary>
		/// 
		/// </summary>
		private bool? _naimohao;
		
		/// <summary>
		/// 
		/// </summary>
		private bool? _naire;
		
		/// <summary>
		/// 
		/// </summary>
		private bool? _naishi;
		
		/// <summary>
		/// 
		/// </summary>
		private bool? _zuran;
		
		/// <summary>
		/// 
		/// </summary>
		private bool? _waiguan2;
		
		/// <summary>
		/// 
		/// </summary>
		private bool? _chongji2;
		
		/// <summary>
		/// 
		/// </summary>
		private bool? _jinmi;
		
		/// <summary>
		/// 
		/// </summary>
		private bool? _toudai;
		
		/// <summary>
		/// 
		/// </summary>
		private bool? _naixiaodu;
		
		/// <summary>
		/// 
		/// </summary>
		private bool? _gouzao;
		
		/// <summary>
		/// 
		/// </summary>
		private bool? _cailiao;
		
		/// <summary>
		/// 
		/// </summary>
		private bool? _jihao;
		
		/// <summary>
		/// 
		/// </summary>
		private bool? _shouce;
		
		/// <summary>
		/// 员工
		/// </summary>
		private Employee _employee1;
		/// <summary>
		/// 员工
		/// </summary>
		private Employee _employee2;
		/// <summary>
		/// 销售订单
		/// </summary>
		private InvoiceXO _invoiceXO;
		/// <summary>
		/// 产品
		/// </summary>
		private Product _product;
		 
		#endregion
		
		#region Properties
		
		/// <summary>
		/// 
		/// </summary>
		public string JISDataInputId
		{
			get 
			{
				return this._jISDataInputId;
			}
			set 
			{
				this._jISDataInputId = value;
			}
		}

		/// <summary>
		/// 
		/// </summary>
		public DateTime? JISDataInputDate
		{
			get 
			{
				return this._jISDataInputDate;
			}
			set 
			{
				this._jISDataInputDate = value;
			}
		}

		/// <summary>
		/// 
		/// </summary>
		public string InvoiceXOId
		{
			get 
			{
				return this._invoiceXOId;
			}
			set 
			{
				this._invoiceXOId = value;
			}
		}

		/// <summary>
		/// 
		/// </summary>
		public string ProductId
		{
			get 
			{
				return this._productId;
			}
			set 
			{
				this._productId = value;
			}
		}

		/// <summary>
		/// 
		/// </summary>
		public DateTime? InsertTime
		{
			get 
			{
				return this._insertTime;
			}
			set 
			{
				this._insertTime = value;
			}
		}

		/// <summary>
		/// 
		/// </summary>
		public DateTime? UpdateTime
		{
			get 
			{
				return this._updateTime;
			}
			set 
			{
				this._updateTime = value;
			}
		}

		/// <summary>
		/// 
		/// </summary>
		public double? InvoiceQuantiy
		{
			get 
			{
				return this._invoiceQuantiy;
			}
			set 
			{
				this._invoiceQuantiy = value;
			}
		}

		/// <summary>
		/// 
		/// </summary>
		public double? TestQuantity
		{
			get 
			{
				return this._testQuantity;
			}
			set 
			{
				this._testQuantity = value;
			}
		}

		/// <summary>
		/// 
		/// </summary>
		public string Color
		{
			get 
			{
				return this._color;
			}
			set 
			{
				this._color = value;
			}
		}

		/// <summary>
		/// 
		/// </summary>
		public string Effect
		{
			get 
			{
				return this._effect;
			}
			set 
			{
				this._effect = value;
			}
		}

		/// <summary>
		/// 
		/// </summary>
		public string EmployeeId1
		{
			get 
			{
				return this._employeeId1;
			}
			set 
			{
				this._employeeId1 = value;
			}
		}

		/// <summary>
		/// 
		/// </summary>
		public string EmployeeId2
		{
			get 
			{
				return this._employeeId2;
			}
			set 
			{
				this._employeeId2 = value;
			}
		}

		/// <summary>
		/// 
		/// </summary>
		public bool? Waiguan1
		{
			get 
			{
				return this._waiguan1;
			}
			set 
			{
				this._waiguan1 = value;
			}
		}

		/// <summary>
		/// 
		/// </summary>
		public bool? Lingjingdu
		{
			get 
			{
				return this._lingjingdu;
			}
			set 
			{
				this._lingjingdu = value;
			}
		}

		/// <summary>
		/// 
		/// </summary>
		public bool? Quguangdu
		{
			get 
			{
				return this._quguangdu;
			}
			set 
			{
				this._quguangdu = value;
			}
		}

		/// <summary>
		/// 
		/// </summary>
		public bool? Sanguangdu
		{
			get 
			{
				return this._sanguangdu;
			}
			set 
			{
				this._sanguangdu = value;
			}
		}

		/// <summary>
		/// 
		/// </summary>
		public bool? Toushilv
		{
			get 
			{
				return this._toushilv;
			}
			set 
			{
				this._toushilv = value;
			}
		}

		/// <summary>
		/// 
		/// </summary>
		public bool? Chongji1
		{
			get 
			{
				return this._chongji1;
			}
			set 
			{
				this._chongji1 = value;
			}
		}

		/// <summary>
		/// 
		/// </summary>
		public bool? Naimohao
		{
			get 
			{
				return this._naimohao;
			}
			set 
			{
				this._naimohao = value;
			}
		}

		/// <summary>
		/// 
		/// </summary>
		public bool? Naire
		{
			get 
			{
				return this._naire;
			}
			set 
			{
				this._naire = value;
			}
		}

		/// <summary>
		/// 
		/// </summary>
		public bool? Naishi
		{
			get 
			{
				return this._naishi;
			}
			set 
			{
				this._naishi = value;
			}
		}

		/// <summary>
		/// 
		/// </summary>
		public bool? Zuran
		{
			get 
			{
				return this._zuran;
			}
			set 
			{
				this._zuran = value;
			}
		}

		/// <summary>
		/// 
		/// </summary>
		public bool? Waiguan2
		{
			get 
			{
				return this._waiguan2;
			}
			set 
			{
				this._waiguan2 = value;
			}
		}

		/// <summary>
		/// 
		/// </summary>
		public bool? Chongji2
		{
			get 
			{
				return this._chongji2;
			}
			set 
			{
				this._chongji2 = value;
			}
		}

		/// <summary>
		/// 
		/// </summary>
		public bool? Jinmi
		{
			get 
			{
				return this._jinmi;
			}
			set 
			{
				this._jinmi = value;
			}
		}

		/// <summary>
		/// 
		/// </summary>
		public bool? Toudai
		{
			get 
			{
				return this._toudai;
			}
			set 
			{
				this._toudai = value;
			}
		}

		/// <summary>
		/// 
		/// </summary>
		public bool? Naixiaodu
		{
			get 
			{
				return this._naixiaodu;
			}
			set 
			{
				this._naixiaodu = value;
			}
		}

		/// <summary>
		/// 
		/// </summary>
		public bool? Gouzao
		{
			get 
			{
				return this._gouzao;
			}
			set 
			{
				this._gouzao = value;
			}
		}

		/// <summary>
		/// 
		/// </summary>
		public bool? Cailiao
		{
			get 
			{
				return this._cailiao;
			}
			set 
			{
				this._cailiao = value;
			}
		}

		/// <summary>
		/// 
		/// </summary>
		public bool? Jihao
		{
			get 
			{
				return this._jihao;
			}
			set 
			{
				this._jihao = value;
			}
		}

		/// <summary>
		/// 
		/// </summary>
		public bool? Shouce
		{
			get 
			{
				return this._shouce;
			}
			set 
			{
				this._shouce = value;
			}
		}
	
		/// <summary>
		/// 员工
		/// </summary>
		public virtual Employee Employee1
		{
			get
			{
				return this._employee1;
			}
			set
			{
				this._employee1 = value;
			}
			
		}
		/// <summary>
		/// 员工
		/// </summary>
		public virtual Employee Employee2
		{
			get
			{
				return this._employee2;
			}
			set
			{
				this._employee2 = value;
			}
			
		}
		/// <summary>
		/// 销售订单
		/// </summary>
		public virtual InvoiceXO InvoiceXO
		{
			get
			{
				return this._invoiceXO;
			}
			set
			{
				this._invoiceXO = value;
			}
			
		}
		/// <summary>
		/// 产品
		/// </summary>
		public virtual Product Product
		{
			get
			{
				return this._product;
			}
			set
			{
				this._product = value;
			}
			
		}
		/// <summary>
		/// 
		/// </summary>
		public readonly static string PRO_JISDataInputId = "JISDataInputId";
		
		/// <summary>
		/// 
		/// </summary>
		public readonly static string PRO_JISDataInputDate = "JISDataInputDate";
		
		/// <summary>
		/// 
		/// </summary>
		public readonly static string PRO_InvoiceXOId = "InvoiceXOId";
		
		/// <summary>
		/// 
		/// </summary>
		public readonly static string PRO_ProductId = "ProductId";
		
		/// <summary>
		/// 
		/// </summary>
		public readonly static string PRO_InsertTime = "InsertTime";
		
		/// <summary>
		/// 
		/// </summary>
		public readonly static string PRO_UpdateTime = "UpdateTime";
		
		/// <summary>
		/// 
		/// </summary>
		public readonly static string PRO_InvoiceQuantiy = "InvoiceQuantiy";
		
		/// <summary>
		/// 
		/// </summary>
		public readonly static string PRO_TestQuantity = "TestQuantity";
		
		/// <summary>
		/// 
		/// </summary>
		public readonly static string PRO_Color = "Color";
		
		/// <summary>
		/// 
		/// </summary>
		public readonly static string PRO_Effect = "Effect";
		
		/// <summary>
		/// 
		/// </summary>
		public readonly static string PRO_EmployeeId1 = "EmployeeId1";
		
		/// <summary>
		/// 
		/// </summary>
		public readonly static string PRO_EmployeeId2 = "EmployeeId2";
		
		/// <summary>
		/// 
		/// </summary>
		public readonly static string PRO_Waiguan1 = "Waiguan1";
		
		/// <summary>
		/// 
		/// </summary>
		public readonly static string PRO_Lingjingdu = "Lingjingdu";
		
		/// <summary>
		/// 
		/// </summary>
		public readonly static string PRO_Quguangdu = "Quguangdu";
		
		/// <summary>
		/// 
		/// </summary>
		public readonly static string PRO_Sanguangdu = "Sanguangdu";
		
		/// <summary>
		/// 
		/// </summary>
		public readonly static string PRO_Toushilv = "Toushilv";
		
		/// <summary>
		/// 
		/// </summary>
		public readonly static string PRO_Chongji1 = "Chongji1";
		
		/// <summary>
		/// 
		/// </summary>
		public readonly static string PRO_Naimohao = "Naimohao";
		
		/// <summary>
		/// 
		/// </summary>
		public readonly static string PRO_Naire = "Naire";
		
		/// <summary>
		/// 
		/// </summary>
		public readonly static string PRO_Naishi = "Naishi";
		
		/// <summary>
		/// 
		/// </summary>
		public readonly static string PRO_Zuran = "Zuran";
		
		/// <summary>
		/// 
		/// </summary>
		public readonly static string PRO_Waiguan2 = "Waiguan2";
		
		/// <summary>
		/// 
		/// </summary>
		public readonly static string PRO_Chongji2 = "Chongji2";
		
		/// <summary>
		/// 
		/// </summary>
		public readonly static string PRO_Jinmi = "Jinmi";
		
		/// <summary>
		/// 
		/// </summary>
		public readonly static string PRO_Toudai = "Toudai";
		
		/// <summary>
		/// 
		/// </summary>
		public readonly static string PRO_Naixiaodu = "Naixiaodu";
		
		/// <summary>
		/// 
		/// </summary>
		public readonly static string PRO_Gouzao = "Gouzao";
		
		/// <summary>
		/// 
		/// </summary>
		public readonly static string PRO_Cailiao = "Cailiao";
		
		/// <summary>
		/// 
		/// </summary>
		public readonly static string PRO_Jihao = "Jihao";
		
		/// <summary>
		/// 
		/// </summary>
		public readonly static string PRO_Shouce = "Shouce";
		

		#endregion
	}
}