//------------------------------------------------------------------------------
//
// 说明： 该文件中的内容是由代码生成器自动生成的，请勿手工修改！
//
// file name：PCAssemblyInspection.autogenerated.cs
// author: mayanjun
// create date：2017-11-05 16:28:13
//
//------------------------------------------------------------------------------
using System;
namespace Book.Model
{
	public partial class PCAssemblyInspection
	{
		#region Data

		/// <summary>
		/// 
		/// </summary>
		private string _pCAssemblyInspectionId;
		
		/// <summary>
		/// 
		/// </summary>
		private DateTime? _pCAssemblyInspectionDate;
		
		/// <summary>
		/// 
		/// </summary>
		private DateTime? _insertTime;
		
		/// <summary>
		/// 
		/// </summary>
		private DateTime? _updateTime;
		
		/// <summary>
		/// 
		/// </summary>
		private string _employeeId;
		
		/// <summary>
		/// 
		/// </summary>
		private string _invoiceCusId;
		
		/// <summary>
		/// 
		/// </summary>
		private string _pronoteHeaderId;
		
		/// <summary>
		/// 
		/// </summary>
		private string _note;

        private string _employeeId1;
		
		/// <summary>
		/// 员工
		/// </summary>
		private Employee _employee;
		/// <summary>
		/// 生产通知头
		/// </summary>
		private PronoteHeader _pronoteHeader;

        private Employee _employee1;

        //2018年2月23日14:31:27
        private string _customerId;

        private Customer _customer;

		#endregion
		
		#region Properties
		
		/// <summary>
		/// 
		/// </summary>
		public string PCAssemblyInspectionId
		{
			get 
			{
				return this._pCAssemblyInspectionId;
			}
			set 
			{
				this._pCAssemblyInspectionId = value;
			}
		}

		/// <summary>
		/// 
		/// </summary>
		public DateTime? PCAssemblyInspectionDate
		{
			get 
			{
				return this._pCAssemblyInspectionDate;
			}
			set 
			{
				this._pCAssemblyInspectionDate = value;
			}
		}

		/// <summary>
		/// 
		/// </summary>
		public DateTime? InsertTime
		{
			get 
			{
				return this._insertTime;
			}
			set 
			{
				this._insertTime = value;
			}
		}

		/// <summary>
		/// 
		/// </summary>
		public DateTime? UpdateTime
		{
			get 
			{
				return this._updateTime;
			}
			set 
			{
				this._updateTime = value;
			}
		}

		/// <summary>
		/// 
		/// </summary>
		public string EmployeeId
		{
			get 
			{
				return this._employeeId;
			}
			set 
			{
				this._employeeId = value;
			}
		}

		/// <summary>
		/// 
		/// </summary>
		public string InvoiceCusId
		{
			get 
			{
				return this._invoiceCusId;
			}
			set 
			{
				this._invoiceCusId = value;
			}
		}

		/// <summary>
		/// 
		/// </summary>
        public string PronoteHeaderId
        {
            get
            {
                return this._pronoteHeaderId;
            }
            set
            {
                this._pronoteHeaderId = value;
            }
        }

		/// <summary>
		/// 
		/// </summary>
		public string Note
		{
			get 
			{
				return this._note;
			}
			set 
			{
				this._note = value;
			}
        }

        public string EmployeeId1
        {
            get { return _employeeId1; }
            set { _employeeId1 = value; }
        }
	
		/// <summary>
		/// 员工
		/// </summary>
		public virtual Employee Employee
		{
			get
			{
				return this._employee;
			}
			set
			{
				this._employee = value;
			}
			
		}
		/// <summary>
		/// 生产通知头
		/// </summary>
        public virtual PronoteHeader PronoteHeader
        {
            get
            {
                return this._pronoteHeader;
            }
            set
            {
                this._pronoteHeader = value;
            }

        }

        public Employee Employee1
        {
            get { return _employee1; }
            set { _employee1 = value; }
        }

        public string CustomerId
        {
            get
            {
                return this._customerId;
            }
            set
            {
                this._customerId = value;
            }
        }

        public virtual Customer Customer
        {
            get
            {
                return this._customer;
            }
            set
            {
                this._customer = value;
            }

        }
		 
		/// <summary>
		/// 
		/// </summary>
		public readonly static string PRO_PCAssemblyInspectionId = "PCAssemblyInspectionId";
		
		/// <summary>
		/// 
		/// </summary>
		public readonly static string PRO_PCAssemblyInspectionDate = "PCAssemblyInspectionDate";
		
		/// <summary>
		/// 
		/// </summary>
		public readonly static string PRO_InsertTime = "InsertTime";
		
		/// <summary>
		/// 
		/// </summary>
		public readonly static string PRO_UpdateTime = "UpdateTime";
		
		/// <summary>
		/// 
		/// </summary>
		public readonly static string PRO_EmployeeId = "EmployeeId";
		
		/// <summary>
		/// 
		/// </summary>
		public readonly static string PRO_InvoiceCusId = "InvoiceCusId";
		
		/// <summary>
		/// 
		/// </summary>
		public readonly static string PRO_PronoteHeaderId = "PronoteHeaderId";
		
		/// <summary>
		/// 
		/// </summary>
		public readonly static string PRO_Note = "Note";

        public readonly static string PRO_EmployeeId1 = "EmployeeId1";

        public readonly static string PRO_CustomerId = "CustomerId";

		#endregion
	}
}