//------------------------------------------------------------------------------
//
// 说明： 该文件中的内容是由代码生成器自动生成的，请勿手工修改！
//
// file name：PCAssemblyInspectionDetail.autogenerated.cs
// author: mayanjun
// create date：2017-11-05 16:28:13
//
//------------------------------------------------------------------------------
using System;
namespace Book.Model
{
	public partial class PCAssemblyInspectionDetail
	{
		#region Data

		/// <summary>
		/// 
		/// </summary>
		private string _pCAssemblyInspectionDetailId;
		
		/// <summary>
		/// 
		/// </summary>
		private string _pCAssemblyInspectionId;
		
		/// <summary>
		/// 
		/// </summary>
		private DateTime? _pCAssemblyInspectionDetailDate;
		
		/// <summary>
		/// 
		/// </summary>
		private string _productId;
		
		/// <summary>
		/// 
		/// </summary>
		private string _customerId;
		
		/// <summary>
		/// 
		/// </summary>
		private decimal? _checkNum;
		
		/// <summary>
		/// 
		/// </summary>
		private string _waiguan;
		
		/// <summary>
		/// 
		/// </summary>
		private string _jiagongbie;
		
		/// <summary>
		/// 
		/// </summary>
		private string _jiao;
		
		/// <summary>
		/// 
		/// </summary>
		private string _shensuojiao;
		
		/// <summary>
		/// 
		/// </summary>
		private string _luosi;
		
		/// <summary>
		/// 
		/// </summary>
		private string _cashang;
		
		/// <summary>
		/// 
		/// </summary>
		private string _kuang;
		
		/// <summary>
		/// 
		/// </summary>
		private string _bidian;
		
		/// <summary>
		/// 
		/// </summary>
		private string _baozhuangdai;
		
		/// <summary>
		/// 
		/// </summary>
		private string _tiaomabiao;
		
		/// <summary>
		/// 
		/// </summary>
		private string _zhengcemai;
		
		/// <summary>
		/// 
		/// </summary>
		private string _chongji;
		
		/// <summary>
		/// 
		/// </summary>
		private decimal? _passNum;
		
		/// <summary>
		/// 
		/// </summary>
		private string _employeeId;
		
		/// <summary>
		/// 
		/// </summary>
		private string _note;
		
		/// <summary>
		/// 客户
		/// </summary>
		private Customer _customer;
		/// <summary>
		/// 员工
		/// </summary>
		private Employee _employee;
		/// <summary>
		/// 
		/// </summary>
		private PCAssemblyInspection _pCAssemblyInspection;
		/// <summary>
		/// 产品
		/// </summary>
		private Product _product;


        //2018年2月23日14:30:02
        private string _pronoteHeaderId;

        private PronoteHeader _pronoteHeader;
		 
		#endregion
		
		#region Properties
		
		/// <summary>
		/// 
		/// </summary>
		public string PCAssemblyInspectionDetailId
		{
			get 
			{
				return this._pCAssemblyInspectionDetailId;
			}
			set 
			{
				this._pCAssemblyInspectionDetailId = value;
			}
		}

		/// <summary>
		/// 
		/// </summary>
		public string PCAssemblyInspectionId
		{
			get 
			{
				return this._pCAssemblyInspectionId;
			}
			set 
			{
				this._pCAssemblyInspectionId = value;
			}
		}

		/// <summary>
		/// 
		/// </summary>
		public DateTime? PCAssemblyInspectionDetailDate
		{
			get 
			{
				return this._pCAssemblyInspectionDetailDate;
			}
			set 
			{
				this._pCAssemblyInspectionDetailDate = value;
			}
		}

		/// <summary>
		/// 
		/// </summary>
		public string ProductId
		{
			get 
			{
				return this._productId;
			}
			set 
			{
				this._productId = value;
			}
		}

		/// <summary>
		/// 
		/// </summary>
		public string CustomerId
		{
			get 
			{
				return this._customerId;
			}
			set 
			{
				this._customerId = value;
			}
		}

		/// <summary>
		/// 
		/// </summary>
		public decimal? CheckNum
		{
			get 
			{
				return this._checkNum;
			}
			set 
			{
				this._checkNum = value;
			}
		}

		/// <summary>
		/// 
		/// </summary>
		public string Waiguan
		{
			get 
			{
				return this._waiguan;
			}
			set 
			{
				this._waiguan = value;
			}
		}

		/// <summary>
		/// 
		/// </summary>
		public string Jiagongbie
		{
			get 
			{
				return this._jiagongbie;
			}
			set 
			{
				this._jiagongbie = value;
			}
		}

		/// <summary>
		/// 
		/// </summary>
		public string Jiao
		{
			get 
			{
				return this._jiao;
			}
			set 
			{
				this._jiao = value;
			}
		}

		/// <summary>
		/// 
		/// </summary>
		public string Shensuojiao
		{
			get 
			{
				return this._shensuojiao;
			}
			set 
			{
				this._shensuojiao = value;
			}
		}

		/// <summary>
		/// 
		/// </summary>
		public string Luosi
		{
			get 
			{
				return this._luosi;
			}
			set 
			{
				this._luosi = value;
			}
		}

		/// <summary>
		/// 
		/// </summary>
		public string Cashang
		{
			get 
			{
				return this._cashang;
			}
			set 
			{
				this._cashang = value;
			}
		}

		/// <summary>
		/// 
		/// </summary>
		public string Kuang
		{
			get 
			{
				return this._kuang;
			}
			set 
			{
				this._kuang = value;
			}
		}

		/// <summary>
		/// 
		/// </summary>
		public string Bidian
		{
			get 
			{
				return this._bidian;
			}
			set 
			{
				this._bidian = value;
			}
		}

		/// <summary>
		/// 
		/// </summary>
		public string Baozhuangdai
		{
			get 
			{
				return this._baozhuangdai;
			}
			set 
			{
				this._baozhuangdai = value;
			}
		}

		/// <summary>
		/// 
		/// </summary>
		public string Tiaomabiao
		{
			get 
			{
				return this._tiaomabiao;
			}
			set 
			{
				this._tiaomabiao = value;
			}
		}

		/// <summary>
		/// 
		/// </summary>
		public string Zhengcemai
		{
			get 
			{
				return this._zhengcemai;
			}
			set 
			{
				this._zhengcemai = value;
			}
		}

		/// <summary>
		/// 
		/// </summary>
		public string Chongji
		{
			get 
			{
				return this._chongji;
			}
			set 
			{
				this._chongji = value;
			}
		}

		/// <summary>
		/// 
		/// </summary>
		public decimal? PassNum
		{
			get 
			{
				return this._passNum;
			}
			set 
			{
				this._passNum = value;
			}
		}

		/// <summary>
		/// 
		/// </summary>
		public string EmployeeId
		{
			get 
			{
				return this._employeeId;
			}
			set 
			{
				this._employeeId = value;
			}
		}

		/// <summary>
		/// 
		/// </summary>
		public string Note
		{
			get 
			{
				return this._note;
			}
			set 
			{
				this._note = value;
			}
		}
	
		/// <summary>
		/// 客户
		/// </summary>
		public virtual Customer Customer
		{
			get
			{
				return this._customer;
			}
			set
			{
				this._customer = value;
			}
			
		}
		/// <summary>
		/// 员工
		/// </summary>
		public virtual Employee Employee
		{
			get
			{
				return this._employee;
			}
			set
			{
				this._employee = value;
			}
			
		}
		/// <summary>
		/// 
		/// </summary>
		public virtual PCAssemblyInspection PCAssemblyInspection
		{
			get
			{
				return this._pCAssemblyInspection;
			}
			set
			{
				this._pCAssemblyInspection = value;
			}
			
		}
		/// <summary>
		/// 产品
		/// </summary>
		public virtual Product Product
		{
			get
			{
				return this._product;
			}
			set
			{
				this._product = value;
			}
			
		}

        public string PronoteHeaderId
        {
            get
            {
                return this._pronoteHeaderId;
            }
            set
            {
                this._pronoteHeaderId = value;
            }
        }

        public virtual PronoteHeader PronoteHeader
        {
            get
            {
                return this._pronoteHeader;
            }
            set
            {
                this._pronoteHeader = value;
            }

        }

		/// <summary>
		/// 
		/// </summary>
		public readonly static string PRO_PCAssemblyInspectionDetailId = "PCAssemblyInspectionDetailId";
		
		/// <summary>
		/// 
		/// </summary>
		public readonly static string PRO_PCAssemblyInspectionId = "PCAssemblyInspectionId";
		
		/// <summary>
		/// 
		/// </summary>
		public readonly static string PRO_PCAssemblyInspectionDetailDate = "PCAssemblyInspectionDetailDate";
		
		/// <summary>
		/// 
		/// </summary>
		public readonly static string PRO_ProductId = "ProductId";
		
		/// <summary>
		/// 
		/// </summary>
		public readonly static string PRO_CustomerId = "CustomerId";
		
		/// <summary>
		/// 
		/// </summary>
		public readonly static string PRO_CheckNum = "CheckNum";
		
		/// <summary>
		/// 
		/// </summary>
		public readonly static string PRO_Waiguan = "Waiguan";
		
		/// <summary>
		/// 
		/// </summary>
		public readonly static string PRO_Jiagongbie = "Jiagongbie";
		
		/// <summary>
		/// 
		/// </summary>
		public readonly static string PRO_Jiao = "Jiao";
		
		/// <summary>
		/// 
		/// </summary>
		public readonly static string PRO_Shensuojiao = "Shensuojiao";
		
		/// <summary>
		/// 
		/// </summary>
		public readonly static string PRO_Luosi = "Luosi";
		
		/// <summary>
		/// 
		/// </summary>
		public readonly static string PRO_Cashang = "Cashang";
		
		/// <summary>
		/// 
		/// </summary>
		public readonly static string PRO_Kuang = "Kuang";
		
		/// <summary>
		/// 
		/// </summary>
		public readonly static string PRO_Bidian = "Bidian";
		
		/// <summary>
		/// 
		/// </summary>
		public readonly static string PRO_Baozhuangdai = "Baozhuangdai";
		
		/// <summary>
		/// 
		/// </summary>
		public readonly static string PRO_Tiaomabiao = "Tiaomabiao";
		
		/// <summary>
		/// 
		/// </summary>
		public readonly static string PRO_Zhengcemai = "Zhengcemai";
		
		/// <summary>
		/// 
		/// </summary>
		public readonly static string PRO_Chongji = "Chongji";
		
		/// <summary>
		/// 
		/// </summary>
		public readonly static string PRO_PassNum = "PassNum";
		
		/// <summary>
		/// 
		/// </summary>
		public readonly static string PRO_EmployeeId = "EmployeeId";
		
		/// <summary>
		/// 
		/// </summary>
		public readonly static string PRO_Note = "Note";

        public readonly static string PRO_PronoteHeaderId = "PronoteHeaderId";
		#endregion
	}
}