//------------------------------------------------------------------------------
//
// 说明： 该文件中的内容是由代码生成器自动生成的，请勿手工修改！
//
// file name：PCDataInput.autogenerated.cs
// author: mayanjun
// create date：2015/1/18 下午 08:12:17
//
//------------------------------------------------------------------------------
using System;
namespace Book.Model
{
    public partial class PCDataInput
    {
        #region Data

        /// <summary>
        /// 
        /// </summary>
        private string _pCDataInputId;

        /// <summary>
        /// 
        /// </summary>
        private DateTime? _pCDataInputDate;

        /// <summary>
        /// 
        /// </summary>
        private string _pronoteHeaderId;

        /// <summary>
        /// 
        /// </summary>
        private string _invoiceCusId;

        /// <summary>
        /// 
        /// </summary>
        private string _productId;

        /// <summary>
        /// 
        /// </summary>
        private decimal? _testQuantity;

        /// <summary>
        /// 
        /// </summary>
        private string _checkStandard;

        private string _customerShortName;

        private decimal? _orderQuantity;

        private string _employeeId;

        private string _employeeId2;

        private string _employeeId3;

        /// <summary>
        /// 
        /// </summary>
        private DateTime? _insertTime;

        /// <summary>
        /// 
        /// </summary>
        private DateTime? _updateTime;

        /// <summary>
        /// 产品
        /// </summary>
        private Product _product;
        /// <summary>
        /// 生产通知头
        /// </summary>
        private PronoteHeader _pronoteHeader;

        private Employee _employee;

        private Employee _employee2;

        private Employee _employee3;

        #endregion

        #region Properties

        /// <summary>
        /// 
        /// </summary>
        public string PCDataInputId
        {
            get
            {
                return this._pCDataInputId;
            }
            set
            {
                this._pCDataInputId = value;
            }
        }

        /// <summary>
        /// 
        /// </summary>
        public DateTime? PCDataInputDate
        {
            get
            {
                return this._pCDataInputDate;
            }
            set
            {
                this._pCDataInputDate = value;
            }
        }

        /// <summary>
        /// 
        /// </summary>
        public string PronoteHeaderId
        {
            get
            {
                return this._pronoteHeaderId;
            }
            set
            {
                this._pronoteHeaderId = value;
            }
        }

        /// <summary>
        /// 
        /// </summary>
        public string InvoiceCusId
        {
            get
            {
                return this._invoiceCusId;
            }
            set
            {
                this._invoiceCusId = value;
            }
        }

        /// <summary>
        /// 
        /// </summary>
        public string ProductId
        {
            get
            {
                return this._productId;
            }
            set
            {
                this._productId = value;
            }
        }

        /// <summary>
        /// 
        /// </summary>
        public decimal? TestQuantity
        {
            get
            {
                return this._testQuantity;
            }
            set
            {
                this._testQuantity = value;
            }
        }

        /// <summary>
        /// 
        /// </summary>
        public string CheckStandard
        {
            get
            {
                return this._checkStandard;
            }
            set
            {
                this._checkStandard = value;
            }
        }

        public string CustomerShortName
        {
            get { return _customerShortName; }
            set { _customerShortName = value; }
        }

        public decimal? OrderQuantity
        {
            get { return _orderQuantity; }
            set { _orderQuantity = value; }
        }

        public string EmployeeId
        {
            get { return _employeeId; }
            set { _employeeId = value; }
        }

        public string EmployeeId2
        {
            get { return _employeeId2; }
            set { _employeeId2 = value; }
        }

        public string EmployeeId3
        {
            get { return _employeeId3; }
            set { _employeeId3 = value; }
        }

        /// <summary>
        /// 
        /// </summary>
        public DateTime? InsertTime
        {
            get
            {
                return this._insertTime;
            }
            set
            {
                this._insertTime = value;
            }
        }

        /// <summary>
        /// 
        /// </summary>
        public DateTime? UpdateTime
        {
            get
            {
                return this._updateTime;
            }
            set
            {
                this._updateTime = value;
            }
        }

        /// <summary>
        /// 产品
        /// </summary>
        public virtual Product Product
        {
            get
            {
                return this._product;
            }
            set
            {
                this._product = value;
            }

        }
        /// <summary>
        /// 生产通知头
        /// </summary>
        public virtual PronoteHeader PronoteHeader
        {
            get
            {
                return this._pronoteHeader;
            }
            set
            {
                this._pronoteHeader = value;
            }

        }

        public Employee Employee
        {
            get { return _employee; }
            set { _employee = value; }
        }

        public Employee Employee2
        {
            get { return _employee2; }
            set { _employee2 = value; }
        }

        public Employee Employee3
        {
            get { return _employee3; }
            set { _employee3 = value; }
        }

        /// <summary>
        /// 
        /// </summary>
        public readonly static string PRO_PCDataInputId = "PCDataInputId";

        /// <summary>
        /// 
        /// </summary>
        public readonly static string PRO_PCDataInputDate = "PCDataInputDate";

        /// <summary>
        /// 
        /// </summary>
        public readonly static string PRO_PronoteHeaderId = "PronoteHeaderId";

        /// <summary>
        /// 
        /// </summary>
        public readonly static string PRO_InvoiceCusId = "InvoiceCusId";

        /// <summary>
        /// 
        /// </summary>
        public readonly static string PRO_ProductId = "ProductId";

        /// <summary>
        /// 
        /// </summary>
        public readonly static string PRO_TestQuantity = "TestQuantity";

        /// <summary>
        /// 
        /// </summary>
        public readonly static string PRO_CheckStandard = "CheckStandard";

        /// <summary>
        /// 
        /// </summary>
        public readonly static string PRO_InsertTime = "InsertTime";

        /// <summary>
        /// 
        /// </summary>
        public readonly static string PRO_UpdateTime = "UpdateTime";

        public readonly static string PRO_CustomerShortName = "CustomerShortName";

        public readonly static string PRO_OrderQuantity = "OrderQuantity";

        public readonly static string PRO_EmployeeId = "EmployeeId";
        public readonly static string PRO_EmployeeId2 = "EmployeeId2";
        public readonly static string PRO_EmployeeId3 = "EmployeeId3";
        #endregion
    }
}