//------------------------------------------------------------------------------
//
// 说明： 该文件中的内容是由代码生成器自动生成的，请勿手工修改！
//
// file name：PCDefinition.autogenerated.cs
// author: mayanjun
// create date：2015/1/18 下午 08:12:17
//
//------------------------------------------------------------------------------
using System;
namespace Book.Model
{
	public partial class PCDefinition
	{
		#region Data

		/// <summary>
		/// 
		/// </summary>
		private string _pCDefinitionId;
		
		/// <summary>
		/// 
		/// </summary>
		private string _pCDataInputId;
		
		/// <summary>
		/// 
		/// </summary>
		private string _noId;
		
		/// <summary>
		/// 
		/// </summary>
		private decimal? _leftDefinition;
		
		/// <summary>
		/// 
		/// </summary>
		private decimal? _rightDefinition;
		
		/// <summary>
		/// 
		/// </summary>
		private decimal? _leftD1;
		
		/// <summary>
		/// 
		/// </summary>
		private decimal? _rightD1;
		
		/// <summary>
		/// 
		/// </summary>
		private decimal? _leftD2;
		
		/// <summary>
		/// 
		/// </summary>
		private decimal? _rightD2;
		
		/// <summary>
		/// 
		/// </summary>
		private string _leftVisibility;
		
		/// <summary>
		/// 
		/// </summary>
		private string _rightVisibility;
		
		/// <summary>
		/// 
		/// </summary>
		private PCDataInput _pCDataInput;
		 
		#endregion
		
		#region Properties
		
		/// <summary>
		/// 
		/// </summary>
		public string PCDefinitionId
		{
			get 
			{
				return this._pCDefinitionId;
			}
			set 
			{
				this._pCDefinitionId = value;
			}
		}

		/// <summary>
		/// 
		/// </summary>
		public string PCDataInputId
		{
			get 
			{
				return this._pCDataInputId;
			}
			set 
			{
				this._pCDataInputId = value;
			}
		}

		/// <summary>
		/// 
		/// </summary>
		public string NoId
		{
			get 
			{
				return this._noId;
			}
			set 
			{
				this._noId = value;
			}
		}

		/// <summary>
		/// 
		/// </summary>
		public decimal? LeftDefinition
		{
			get 
			{
				return this._leftDefinition;
			}
			set 
			{
				this._leftDefinition = value;
			}
		}

		/// <summary>
		/// 
		/// </summary>
		public decimal? RightDefinition
		{
			get 
			{
				return this._rightDefinition;
			}
			set 
			{
				this._rightDefinition = value;
			}
		}

		/// <summary>
		/// 
		/// </summary>
		public decimal? LeftD1
		{
			get 
			{
				return this._leftD1;
			}
			set 
			{
				this._leftD1 = value;
			}
		}

		/// <summary>
		/// 
		/// </summary>
		public decimal? RightD1
		{
			get 
			{
				return this._rightD1;
			}
			set 
			{
				this._rightD1 = value;
			}
		}

		/// <summary>
		/// 
		/// </summary>
		public decimal? LeftD2
		{
			get 
			{
				return this._leftD2;
			}
			set 
			{
				this._leftD2 = value;
			}
		}

		/// <summary>
		/// 
		/// </summary>
		public decimal? RightD2
		{
			get 
			{
				return this._rightD2;
			}
			set 
			{
				this._rightD2 = value;
			}
		}

		/// <summary>
		/// 
		/// </summary>
		public string LeftVisibility
		{
			get 
			{
				return this._leftVisibility;
			}
			set 
			{
				this._leftVisibility = value;
			}
		}

		/// <summary>
		/// 
		/// </summary>
		public string RightVisibility
		{
			get 
			{
				return this._rightVisibility;
			}
			set 
			{
				this._rightVisibility = value;
			}
		}
	
		/// <summary>
		/// 
		/// </summary>
		public virtual PCDataInput PCDataInput
		{
			get
			{
				return this._pCDataInput;
			}
			set
			{
				this._pCDataInput = value;
			}
			
		}
		/// <summary>
		/// 
		/// </summary>
		public readonly static string PRO_PCDefinitionId = "PCDefinitionId";
		
		/// <summary>
		/// 
		/// </summary>
		public readonly static string PRO_PCDataInputId = "PCDataInputId";
		
		/// <summary>
		/// 
		/// </summary>
		public readonly static string PRO_NoId = "NoId";
		
		/// <summary>
		/// 
		/// </summary>
		public readonly static string PRO_LeftDefinition = "LeftDefinition";
		
		/// <summary>
		/// 
		/// </summary>
		public readonly static string PRO_RightDefinition = "RightDefinition";
		
		/// <summary>
		/// 
		/// </summary>
		public readonly static string PRO_LeftD1 = "LeftD1";
		
		/// <summary>
		/// 
		/// </summary>
		public readonly static string PRO_RightD1 = "RightD1";
		
		/// <summary>
		/// 
		/// </summary>
		public readonly static string PRO_LeftD2 = "LeftD2";
		
		/// <summary>
		/// 
		/// </summary>
		public readonly static string PRO_RightD2 = "RightD2";
		
		/// <summary>
		/// 
		/// </summary>
		public readonly static string PRO_LeftVisibility = "LeftVisibility";
		
		/// <summary>
		/// 
		/// </summary>
		public readonly static string PRO_RightVisibility = "RightVisibility";
		

		#endregion
	}
}