//------------------------------------------------------------------------------
//
// 说明： 该文件中的内容是由代码生成器自动生成的，请勿手工修改！
//
// file name：PCEarplugsDecibelCheckDetail.autogenerated.cs
// author: mayanjun
// create date：2019/5/12 14:43:55
//
//------------------------------------------------------------------------------
using System;
namespace Book.Model
{
	public partial class PCEarplugsDecibelCheckDetail
	{
		#region Data

		/// <summary>
		/// 
		/// </summary>
		private string _pCEarplugsDecibelCheckDetailId;
		
		/// <summary>
		/// 
		/// </summary>
		private string _pCEarplugsDecibelCheckId;
		
		/// <summary>
		/// 
		/// </summary>
		private string _number;
		
		/// <summary>
		/// 
		/// </summary>
		private DateTime? _testTime;
		
		/// <summary>
		/// 
		/// </summary>
		private string _fromId;
		
		/// <summary>
		/// 
		/// </summary>
		private string _invoiceXOId;
		
		/// <summary>
		/// 
		/// </summary>
		private double? _invoiceXOQuantity;
		
		/// <summary>
		/// 
		/// </summary>
		private string _productId;
		
		/// <summary>
		/// 
		/// </summary>
		private string _productUnit;
		
		/// <summary>
		/// 
		/// </summary>
		private int? _testQuantity;
		
		/// <summary>
		/// 
		/// </summary>
		private decimal _yinpin;
		
		/// <summary>
		/// 
		/// </summary>
		private string _judge;
		
		/// <summary>
		/// 销售订单
		/// </summary>
		private InvoiceXO _invoiceXO;
		/// <summary>
		/// 
		/// </summary>
		private PCEarplugsDecibelCheck _pCEarplugsDecibelCheck;
		/// <summary>
		/// 产品
		/// </summary>
		private Product _product;
		 
		#endregion
		
		#region Properties
		
		/// <summary>
		/// 
		/// </summary>
		public string PCEarplugsDecibelCheckDetailId
		{
			get 
			{
				return this._pCEarplugsDecibelCheckDetailId;
			}
			set 
			{
				this._pCEarplugsDecibelCheckDetailId = value;
			}
		}

		/// <summary>
		/// 
		/// </summary>
		public string PCEarplugsDecibelCheckId
		{
			get 
			{
				return this._pCEarplugsDecibelCheckId;
			}
			set 
			{
				this._pCEarplugsDecibelCheckId = value;
			}
		}

		/// <summary>
		/// 
		/// </summary>
		public string Number
		{
			get 
			{
				return this._number;
			}
			set 
			{
				this._number = value;
			}
		}

		/// <summary>
		/// 
		/// </summary>
		public DateTime? TestTime
		{
			get 
			{
				return this._testTime;
			}
			set 
			{
				this._testTime = value;
			}
		}

		/// <summary>
		/// 
		/// </summary>
		public string FromId
		{
			get 
			{
				return this._fromId;
			}
			set 
			{
				this._fromId = value;
			}
		}

		/// <summary>
		/// 
		/// </summary>
		public string InvoiceXOId
		{
			get 
			{
				return this._invoiceXOId;
			}
			set 
			{
				this._invoiceXOId = value;
			}
		}

		/// <summary>
		/// 
		/// </summary>
		public double? InvoiceXOQuantity
		{
			get 
			{
				return this._invoiceXOQuantity;
			}
			set 
			{
				this._invoiceXOQuantity = value;
			}
		}

		/// <summary>
		/// 
		/// </summary>
		public string ProductId
		{
			get 
			{
				return this._productId;
			}
			set 
			{
				this._productId = value;
			}
		}

		/// <summary>
		/// 
		/// </summary>
		public string ProductUnit
		{
			get 
			{
				return this._productUnit;
			}
			set 
			{
				this._productUnit = value;
			}
		}

		/// <summary>
		/// 
		/// </summary>
		public int? TestQuantity
		{
			get 
			{
				return this._testQuantity;
			}
			set 
			{
				this._testQuantity = value;
			}
		}

		/// <summary>
		/// 
		/// </summary>
        public decimal Yinpin
		{
			get 
			{
				return this._yinpin;
			}
			set 
			{
				this._yinpin = value;
			}
		}

		/// <summary>
		/// 
		/// </summary>
		public string Judge
		{
			get 
			{
				return this._judge;
			}
			set 
			{
				this._judge = value;
			}
		}
	
		/// <summary>
		/// 销售订单
		/// </summary>
		public virtual InvoiceXO InvoiceXO
		{
			get
			{
				return this._invoiceXO;
			}
			set
			{
				this._invoiceXO = value;
			}
			
		}
		/// <summary>
		/// 
		/// </summary>
		public virtual PCEarplugsDecibelCheck PCEarplugsDecibelCheck
		{
			get
			{
				return this._pCEarplugsDecibelCheck;
			}
			set
			{
				this._pCEarplugsDecibelCheck = value;
			}
			
		}
		/// <summary>
		/// 产品
		/// </summary>
		public virtual Product Product
		{
			get
			{
				return this._product;
			}
			set
			{
				this._product = value;
			}
			
		}
		/// <summary>
		/// 
		/// </summary>
		public readonly static string PRO_PCEarplugsDecibelCheckDetailId = "PCEarplugsDecibelCheckDetailId";
		
		/// <summary>
		/// 
		/// </summary>
		public readonly static string PRO_PCEarplugsDecibelCheckId = "PCEarplugsDecibelCheckId";
		
		/// <summary>
		/// 
		/// </summary>
		public readonly static string PRO_Number = "Number";
		
		/// <summary>
		/// 
		/// </summary>
		public readonly static string PRO_TestTime = "TestTime";
		
		/// <summary>
		/// 
		/// </summary>
		public readonly static string PRO_FromId = "FromId";
		
		/// <summary>
		/// 
		/// </summary>
		public readonly static string PRO_InvoiceXOId = "InvoiceXOId";
		
		/// <summary>
		/// 
		/// </summary>
		public readonly static string PRO_InvoiceXOQuantity = "InvoiceXOQuantity";
		
		/// <summary>
		/// 
		/// </summary>
		public readonly static string PRO_ProductId = "ProductId";
		
		/// <summary>
		/// 
		/// </summary>
		public readonly static string PRO_ProductUnit = "ProductUnit";
		
		/// <summary>
		/// 
		/// </summary>
		public readonly static string PRO_TestQuantity = "TestQuantity";
		
		/// <summary>
		/// 
		/// </summary>
		public readonly static string PRO_Yinpin = "Yinpin";
		
		/// <summary>
		/// 
		/// </summary>
		public readonly static string PRO_Judge = "Judge";
		

		#endregion
	}
}