//------------------------------------------------------------------------------
//
// 说明： 该文件中的内容是由代码生成器自动生成的，请勿手工修改！
//
// file name：PCEarplugsStayWireCheck.autogenerated.cs
// author: mayanjun
// create date：2019/5/14 09:57:07
//
//------------------------------------------------------------------------------
using System;
namespace Book.Model
{
	public partial class PCEarplugsStayWireCheck
	{
		#region Data

		/// <summary>
		/// 
		/// </summary>
		private string _pCEarplugsStayWireCheckId;
		
		/// <summary>
		/// 
		/// </summary>
		private DateTime? _pCEarplugsStayWireCheckDate;
		
		/// <summary>
		/// 
		/// </summary>
		private string _employeeId;
		
		/// <summary>
		/// 
		/// </summary>
		private string _note;
		
		/// <summary>
		/// 
		/// </summary>
		private DateTime? _insertTime;
		
		/// <summary>
		/// 
		/// </summary>
		private DateTime? _updateTime;
		
		/// <summary>
		/// 
		/// </summary>
		private int? _auditState;
		
		/// <summary>
		/// 
		/// </summary>
		private string _auditEmpId;

        private string _testCondition;
		
		/// <summary>
		/// 员工
		/// </summary>
		private Employee _auditEmp;
		/// <summary>
		/// 员工
		/// </summary>
		private Employee _employee;
		 
		#endregion
		
		#region Properties
		
		/// <summary>
		/// 
		/// </summary>
		public string PCEarplugsStayWireCheckId
		{
			get 
			{
				return this._pCEarplugsStayWireCheckId;
			}
			set 
			{
				this._pCEarplugsStayWireCheckId = value;
			}
		}

		/// <summary>
		/// 
		/// </summary>
		public DateTime? PCEarplugsStayWireCheckDate
		{
			get 
			{
				return this._pCEarplugsStayWireCheckDate;
			}
			set 
			{
				this._pCEarplugsStayWireCheckDate = value;
			}
		}

		/// <summary>
		/// 
		/// </summary>
		public string EmployeeId
		{
			get 
			{
				return this._employeeId;
			}
			set 
			{
				this._employeeId = value;
			}
		}

		/// <summary>
		/// 
		/// </summary>
		public string Note
		{
			get 
			{
				return this._note;
			}
			set 
			{
				this._note = value;
			}
		}

		/// <summary>
		/// 
		/// </summary>
		public DateTime? InsertTime
		{
			get 
			{
				return this._insertTime;
			}
			set 
			{
				this._insertTime = value;
			}
		}

		/// <summary>
		/// 
		/// </summary>
		public DateTime? UpdateTime
		{
			get 
			{
				return this._updateTime;
			}
			set 
			{
				this._updateTime = value;
			}
		}

		/// <summary>
		/// 
		/// </summary>
		public int? AuditState
		{
			get 
			{
				return this._auditState;
			}
			set 
			{
				this._auditState = value;
			}
		}

		/// <summary>
		/// 
		/// </summary>
		public string AuditEmpId
		{
			get 
			{
				return this._auditEmpId;
			}
			set 
			{
				this._auditEmpId = value;
			}
        }

        public string TestCondition
        {
            get { return _testCondition; }
            set { _testCondition = value; }
        }
	
		/// <summary>
		/// 员工
		/// </summary>
		public virtual Employee AuditEmp
		{
			get
			{
				return this._auditEmp;
			}
			set
			{
				this._auditEmp = value;
			}
			
		}
		/// <summary>
		/// 员工
		/// </summary>
		public virtual Employee Employee
		{
			get
			{
				return this._employee;
			}
			set
			{
				this._employee = value;
			}
			
		}
		/// <summary>
		/// 
		/// </summary>
		public readonly static string PRO_PCEarplugsStayWireCheckId = "PCEarplugsStayWireCheckId";
		
		/// <summary>
		/// 
		/// </summary>
		public readonly static string PRO_PCEarplugsStayWireCheckDate = "PCEarplugsStayWireCheckDate";
		
		/// <summary>
		/// 
		/// </summary>
		public readonly static string PRO_EmployeeId = "EmployeeId";
		
		/// <summary>
		/// 
		/// </summary>
		public readonly static string PRO_Note = "Note";
		
		/// <summary>
		/// 
		/// </summary>
		public readonly static string PRO_InsertTime = "InsertTime";
		
		/// <summary>
		/// 
		/// </summary>
		public readonly static string PRO_UpdateTime = "UpdateTime";
		
		/// <summary>
		/// 
		/// </summary>
		public readonly static string PRO_AuditState = "AuditState";
		
		/// <summary>
		/// 
		/// </summary>
		public readonly static string PRO_AuditEmpId = "AuditEmpId";


        public readonly static string PRO_TestCondition = "TestCondition";
		

		#endregion
	}
}