//------------------------------------------------------------------------------
//
// 说明： 该文件中的内容是由代码生成器自动生成的，请勿手工修改！
//
// file name：PCEarplugsResilienceConditionSet.autogenerated.cs
// author: mayanjun
// create date：2019/6/15 19:29:49
//
//------------------------------------------------------------------------------
using System;
namespace Book.Model
{
	public partial class PCEarplugsResilienceConditionSet
	{
		#region Data

		/// <summary>
		/// 
		/// </summary>
		private string _pCEarplugsResilienceConditionSetId;
		
		/// <summary>
		/// 
		/// </summary>
		private string _pCEarplugsResilienceCheckId;
		
		/// <summary>
		/// 
		/// </summary>
		private DateTime? _insertTime;
		
		/// <summary>
		/// 
		/// </summary>
		private DateTime? _updateTime;
		
		/// <summary>
		/// 
		/// </summary>
		private decimal? _tKY1;
		
		/// <summary>
		/// 
		/// </summary>
		private decimal? _tKY2;
		
		/// <summary>
		/// 
		/// </summary>
		private decimal? _tKY3;
		
		/// <summary>
		/// 
		/// </summary>
		private decimal? _tKY4;
		
		/// <summary>
		/// 
		/// </summary>
		private decimal? _tKY5;
		
		/// <summary>
		/// 
		/// </summary>
		private decimal? _tKY6;
		
		/// <summary>
		/// 
		/// </summary>
		private decimal? _sCR1;
		
		/// <summary>
		/// 
		/// </summary>
		private decimal? _sCR2;
		
		/// <summary>
		/// 
		/// </summary>
		private decimal? _sCR3;
		
		/// <summary>
		/// 
		/// </summary>
		private decimal? _sCR4;
		
		/// <summary>
		/// 
		/// </summary>
		private decimal? _sCR5;
		
		/// <summary>
		/// 
		/// </summary>
		private decimal? _sCR6;
		
		 
		#endregion
		
		#region Properties
		
		/// <summary>
		/// 
		/// </summary>
		public string PCEarplugsResilienceConditionSetId
		{
			get 
			{
				return this._pCEarplugsResilienceConditionSetId;
			}
			set 
			{
				this._pCEarplugsResilienceConditionSetId = value;
			}
		}

		/// <summary>
		/// 
		/// </summary>
		public string PCEarplugsResilienceCheckId
		{
			get 
			{
				return this._pCEarplugsResilienceCheckId;
			}
			set 
			{
				this._pCEarplugsResilienceCheckId = value;
			}
		}

		/// <summary>
		/// 
		/// </summary>
		public DateTime? InsertTime
		{
			get 
			{
				return this._insertTime;
			}
			set 
			{
				this._insertTime = value;
			}
		}

		/// <summary>
		/// 
		/// </summary>
		public DateTime? UpdateTime
		{
			get 
			{
				return this._updateTime;
			}
			set 
			{
				this._updateTime = value;
			}
		}

		/// <summary>
		/// 
		/// </summary>
		public decimal? TKY1
		{
			get 
			{
				return this._tKY1;
			}
			set 
			{
				this._tKY1 = value;
			}
		}

		/// <summary>
		/// 
		/// </summary>
		public decimal? TKY2
		{
			get 
			{
				return this._tKY2;
			}
			set 
			{
				this._tKY2 = value;
			}
		}

		/// <summary>
		/// 
		/// </summary>
		public decimal? TKY3
		{
			get 
			{
				return this._tKY3;
			}
			set 
			{
				this._tKY3 = value;
			}
		}

		/// <summary>
		/// 
		/// </summary>
		public decimal? TKY4
		{
			get 
			{
				return this._tKY4;
			}
			set 
			{
				this._tKY4 = value;
			}
		}

		/// <summary>
		/// 
		/// </summary>
		public decimal? TKY5
		{
			get 
			{
				return this._tKY5;
			}
			set 
			{
				this._tKY5 = value;
			}
		}

		/// <summary>
		/// 
		/// </summary>
		public decimal? TKY6
		{
			get 
			{
				return this._tKY6;
			}
			set 
			{
				this._tKY6 = value;
			}
		}

		/// <summary>
		/// 
		/// </summary>
		public decimal? SCR1
		{
			get 
			{
				return this._sCR1;
			}
			set 
			{
				this._sCR1 = value;
			}
		}

		/// <summary>
		/// 
		/// </summary>
		public decimal? SCR2
		{
			get 
			{
				return this._sCR2;
			}
			set 
			{
				this._sCR2 = value;
			}
		}

		/// <summary>
		/// 
		/// </summary>
		public decimal? SCR3
		{
			get 
			{
				return this._sCR3;
			}
			set 
			{
				this._sCR3 = value;
			}
		}

		/// <summary>
		/// 
		/// </summary>
		public decimal? SCR4
		{
			get 
			{
				return this._sCR4;
			}
			set 
			{
				this._sCR4 = value;
			}
		}

		/// <summary>
		/// 
		/// </summary>
		public decimal? SCR5
		{
			get 
			{
				return this._sCR5;
			}
			set 
			{
				this._sCR5 = value;
			}
		}

		/// <summary>
		/// 
		/// </summary>
		public decimal? SCR6
		{
			get 
			{
				return this._sCR6;
			}
			set 
			{
				this._sCR6 = value;
			}
		}
	
		/// <summary>
		/// 
		/// </summary>
		public readonly static string PRO_PCEarplugsResilienceConditionSetId = "PCEarplugsResilienceConditionSetId";
		
		/// <summary>
		/// 
		/// </summary>
		public readonly static string PRO_PCEarplugsResilienceCheckId = "PCEarplugsResilienceCheckId";
		
		/// <summary>
		/// 
		/// </summary>
		public readonly static string PRO_InsertTime = "InsertTime";
		
		/// <summary>
		/// 
		/// </summary>
		public readonly static string PRO_UpdateTime = "UpdateTime";
		
		/// <summary>
		/// 
		/// </summary>
		public readonly static string PRO_TKY1 = "TKY1";
		
		/// <summary>
		/// 
		/// </summary>
		public readonly static string PRO_TKY2 = "TKY2";
		
		/// <summary>
		/// 
		/// </summary>
		public readonly static string PRO_TKY3 = "TKY3";
		
		/// <summary>
		/// 
		/// </summary>
		public readonly static string PRO_TKY4 = "TKY4";
		
		/// <summary>
		/// 
		/// </summary>
		public readonly static string PRO_TKY5 = "TKY5";
		
		/// <summary>
		/// 
		/// </summary>
		public readonly static string PRO_TKY6 = "TKY6";
		
		/// <summary>
		/// 
		/// </summary>
		public readonly static string PRO_SCR1 = "SCR1";
		
		/// <summary>
		/// 
		/// </summary>
		public readonly static string PRO_SCR2 = "SCR2";
		
		/// <summary>
		/// 
		/// </summary>
		public readonly static string PRO_SCR3 = "SCR3";
		
		/// <summary>
		/// 
		/// </summary>
		public readonly static string PRO_SCR4 = "SCR4";
		
		/// <summary>
		/// 
		/// </summary>
		public readonly static string PRO_SCR5 = "SCR5";
		
		/// <summary>
		/// 
		/// </summary>
		public readonly static string PRO_SCR6 = "SCR6";
		

		#endregion
	}
}