//------------------------------------------------------------------------------
//
// 说明： 该文件中的内容是由代码生成器自动生成的，请勿手工修改！
//
// file name：PCEarplugsResilienceCheckDetail.autogenerated.cs
// author: mayanjun
// create date：2019/5/10 10:49:43
//
//------------------------------------------------------------------------------
using System;
namespace Book.Model
{
    public partial class PCEarplugsResilienceCheckDetail
    {
        #region Data

        /// <summary>
        /// 
        /// </summary>
        private string _pCEarplugsResilienceCheckDetailId;

        /// <summary>
        /// 
        /// </summary>
        private string _pCEarplugsResilienceCheckId;

        private string _number;

        /// <summary>
        /// 
        /// </summary>
        private string _fromId;

        /// <summary>
        /// 
        /// </summary>
        private string _invoiceXOId;

        /// <summary>
        /// 
        /// </summary>
        private double? _invoiceXOQuantity;

        /// <summary>
        /// 
        /// </summary>
        private string _productId;

        /// <summary>
        /// 
        /// </summary>
        private string _productUnit;

        /// <summary>
        /// 
        /// </summary>
        private int? _testQuantity;

        /// <summary>
        /// 
        /// </summary>
        private string _waiguan;

        /// <summary>
        /// 
        /// </summary>
        private string _duise;

        /// <summary>
        /// 
        /// </summary>
        private string _chicun;

        /// <summary>
        /// 
        /// </summary>
        private decimal? _tiekuaiya;

        private decimal? _shoucuorou;

        /// <summary>
        /// 
        /// </summary>
        private string _judge;

        /// <summary>
        /// 销售订单
        /// </summary>
        private InvoiceXO _invoiceXO;
        /// <summary>
        /// 
        /// </summary>
        private PCEarplugsResilienceCheck _pCEarplugsResilienceCheck;
        /// <summary>
        /// 产品
        /// </summary>
        private Product _product;

        #endregion

        #region Properties

        /// <summary>
        /// 
        /// </summary>
        public string PCEarplugsResilienceCheckDetailId
        {
            get
            {
                return this._pCEarplugsResilienceCheckDetailId;
            }
            set
            {
                this._pCEarplugsResilienceCheckDetailId = value;
            }
        }

        /// <summary>
        /// 
        /// </summary>
        public string PCEarplugsResilienceCheckId
        {
            get
            {
                return this._pCEarplugsResilienceCheckId;
            }
            set
            {
                this._pCEarplugsResilienceCheckId = value;
            }
        }

        public string Number
        {
            get { return _number; }
            set { _number = value; }
        }

        /// <summary>
        /// 
        /// </summary>
        public string FromId
        {
            get
            {
                return this._fromId;
            }
            set
            {
                this._fromId = value;
            }
        }

        /// <summary>
        /// 
        /// </summary>
        public string InvoiceXOId
        {
            get
            {
                return this._invoiceXOId;
            }
            set
            {
                this._invoiceXOId = value;
            }
        }

        /// <summary>
        /// 
        /// </summary>
        public double? InvoiceXOQuantity
        {
            get
            {
                return this._invoiceXOQuantity;
            }
            set
            {
                this._invoiceXOQuantity = value;
            }
        }

        /// <summary>
        /// 
        /// </summary>
        public string ProductId
        {
            get
            {
                return this._productId;
            }
            set
            {
                this._productId = value;
            }
        }

        /// <summary>
        /// 
        /// </summary>
        public string ProductUnit
        {
            get
            {
                return this._productUnit;
            }
            set
            {
                this._productUnit = value;
            }
        }

        /// <summary>
        /// 
        /// </summary>
        public int? TestQuantity
        {
            get
            {
                return this._testQuantity;
            }
            set
            {
                this._testQuantity = value;
            }
        }

        /// <summary>
        /// 
        /// </summary>
        public string Waiguan
        {
            get
            {
                return this._waiguan;
            }
            set
            {
                this._waiguan = value;
            }
        }

        /// <summary>
        /// 
        /// </summary>
        public string Duise
        {
            get
            {
                return this._duise;
            }
            set
            {
                this._duise = value;
            }
        }

        /// <summary>
        /// 
        /// </summary>
        public string Chicun
        {
            get
            {
                return this._chicun;
            }
            set
            {
                this._chicun = value;
            }
        }

        /// <summary>
        /// 
        /// </summary>
        public decimal? Tiekuaiya
        {
            get
            {
                return this._tiekuaiya;
            }
            set
            {
                this._tiekuaiya = value;
            }
        }

        public decimal? Shoucuorou
        {
            get { return _shoucuorou; }
            set { _shoucuorou = value; }
        }

        /// <summary>
        /// 
        /// </summary>
        public string Judge
        {
            get
            {
                return this._judge;
            }
            set
            {
                this._judge = value;
            }
        }

        /// <summary>
        /// 销售订单
        /// </summary>
        public virtual InvoiceXO InvoiceXO
        {
            get
            {
                return this._invoiceXO;
            }
            set
            {
                this._invoiceXO = value;
            }

        }
        /// <summary>
        /// 
        /// </summary>
        public virtual PCEarplugsResilienceCheck PCEarplugsResilienceCheck
        {
            get
            {
                return this._pCEarplugsResilienceCheck;
            }
            set
            {
                this._pCEarplugsResilienceCheck = value;
            }

        }
        /// <summary>
        /// 产品
        /// </summary>
        public virtual Product Product
        {
            get
            {
                return this._product;
            }
            set
            {
                this._product = value;
            }

        }
        /// <summary>
        /// 
        /// </summary>
        public readonly static string PRO_PCEarplugsResilienceCheckDetailId = "PCEarplugsResilienceCheckDetailId";

        /// <summary>
        /// 
        /// </summary>
        public readonly static string PRO_PCEarplugsResilienceCheckId = "PCEarplugsResilienceCheckId";

        public readonly static string PRO_Number = "Number";

        /// <summary>
        /// 
        /// </summary>
        public readonly static string PRO_FromId = "FromId";

        /// <summary>
        /// 
        /// </summary>
        public readonly static string PRO_InvoiceXOId = "InvoiceXOId";

        /// <summary>
        /// 
        /// </summary>
        public readonly static string PRO_InvoiceXOQuantity = "InvoiceXOQuantity";

        /// <summary>
        /// 
        /// </summary>
        public readonly static string PRO_ProductId = "ProductId";

        /// <summary>
        /// 
        /// </summary>
        public readonly static string PRO_ProductUnit = "ProductUnit";

        /// <summary>
        /// 
        /// </summary>
        public readonly static string PRO_TestQuantity = "TestQuantity";

        /// <summary>
        /// 
        /// </summary>
        public readonly static string PRO_Waiguan = "Waiguan";

        /// <summary>
        /// 
        /// </summary>
        public readonly static string PRO_Duise = "Duise";

        /// <summary>
        /// 
        /// </summary>
        public readonly static string PRO_Chicun = "Chicun";

        public readonly static string PRO_Tiekuaiya = "Tiekuaiya";

        /// <summary>
        /// 
        /// </summary>
        public readonly static string PRO_Shoucuorou = "Shoucuorou";

        /// <summary>
        /// 
        /// </summary>
        public readonly static string PRO_Judge = "Judge";


        #endregion
    }
}