//------------------------------------------------------------------------------
//
// 说明： 该文件中的内容是由代码生成器自动生成的，请勿手工修改！
//
// file name：PCEarplugsResilienceCheck.autogenerated.cs
// author: mayanjun
// create date：2019/5/10 10:49:43
//
//------------------------------------------------------------------------------
using System;
namespace Book.Model
{
    /// <summary>
    /// 耳塞回弹力测试表
    /// </summary>
	public partial class PCEarplugsResilienceCheck
	{
		#region Data

		/// <summary>
		/// 
		/// </summary>
		private string _pCEarplugsResilienceCheckId;
		
		/// <summary>
		/// 
		/// </summary>
		private DateTime? _pCEarplugsResilienceCheckDate;
		
		/// <summary>
		/// 
		/// </summary>
		private string _employeeId;
		
		/// <summary>
		/// 
		/// </summary>
		private string _note;

        private string _tiekuaiyaCondition;

        private string _shoucuorouCondition;
		
		/// <summary>
		/// 
		/// </summary>
		private DateTime? _insertTime;
		
		/// <summary>
		/// 
		/// </summary>
		private DateTime? _updateTime;
		
		/// <summary>
		/// 员工
		/// </summary>
		private Employee _employee;
		 
		#endregion
		
		#region Properties
		
		/// <summary>
		/// 
		/// </summary>
		public string PCEarplugsResilienceCheckId
		{
			get 
			{
				return this._pCEarplugsResilienceCheckId;
			}
			set 
			{
				this._pCEarplugsResilienceCheckId = value;
			}
		}

		/// <summary>
		/// 
		/// </summary>
		public DateTime? PCEarplugsResilienceCheckDate
		{
			get 
			{
				return this._pCEarplugsResilienceCheckDate;
			}
			set 
			{
				this._pCEarplugsResilienceCheckDate = value;
			}
		}

		/// <summary>
		/// 
		/// </summary>
		public string EmployeeId
		{
			get 
			{
				return this._employeeId;
			}
			set 
			{
				this._employeeId = value;
			}
		}

		/// <summary>
		/// 
		/// </summary>
		public string Note
		{
			get 
			{
				return this._note;
			}
			set 
			{
				this._note = value;
			}
		}

		/// <summary>
		/// 
		/// </summary>
		public DateTime? InsertTime
		{
			get 
			{
				return this._insertTime;
			}
			set 
			{
				this._insertTime = value;
			}
		}

		/// <summary>
		/// 
		/// </summary>
		public DateTime? UpdateTime
		{
			get 
			{
				return this._updateTime;
			}
			set 
			{
				this._updateTime = value;
			}
        }

        public string TiekuaiyaCondition
        {
            get { return _tiekuaiyaCondition; }
            set { _tiekuaiyaCondition = value; }
        }

        public string ShoucuorouCondition
        {
            get { return _shoucuorouCondition; }
            set { _shoucuorouCondition = value; }
        }
	
		/// <summary>
		/// 员工
		/// </summary>
		public virtual Employee Employee
		{
			get
			{
				return this._employee;
			}
			set
			{
				this._employee = value;
			}
			
		}
		/// <summary>
		/// 
		/// </summary>
		public readonly static string PRO_PCEarplugsResilienceCheckId = "PCEarplugsResilienceCheckId";
		
		/// <summary>
		/// 
		/// </summary>
		public readonly static string PRO_PCEarplugsResilienceCheckDate = "PCEarplugsResilienceCheckDate";
		
		/// <summary>
		/// 
		/// </summary>
		public readonly static string PRO_EmployeeId = "EmployeeId";
		
		/// <summary>
		/// 
		/// </summary>
		public readonly static string PRO_Note = "Note";
		
		/// <summary>
		/// 
		/// </summary>
		public readonly static string PRO_InsertTime = "InsertTime";
		
		/// <summary>
		/// 
		/// </summary>
		public readonly static string PRO_UpdateTime = "UpdateTime";


        public readonly static string PRO_TiekuaiyaCondition = "TiekuaiyaCondition";

        public readonly static string PRO_ShoucuorouCondition = "ShoucuorouCondition";

		#endregion
	}
}