//------------------------------------------------------------------------------
//
// 说明： 该文件中的内容是由代码生成器自动生成的，请勿手工修改！
//
// file name：PCEarplugsResilienceWeight.autogenerated.cs
// author: mayanjun
// create date：2019/8/25 22:18:55
//
//------------------------------------------------------------------------------
using System;
namespace Book.Model
{
	public partial class PCEarplugsResilienceWeight
	{
		#region Data

		/// <summary>
		/// 
		/// </summary>
		private string _pCEarplugsResilienceWeightId;
		
		/// <summary>
		/// 
		/// </summary>
		private string _pCEarplugsResilienceCheckId;
		
		/// <summary>
		/// 
		/// </summary>
		private DateTime? _insertTime;
		
		/// <summary>
		/// 
		/// </summary>
		private DateTime? _updateTime;
		
		/// <summary>
		/// 
		/// </summary>
        private decimal? _weight1;
		
		/// <summary>
		/// 
		/// </summary>
        private decimal? _weight2;
		
		/// <summary>
		/// 
		/// </summary>
        private decimal? _weight3;
		
		/// <summary>
		/// 
		/// </summary>
        private decimal? _weight4;
		
		/// <summary>
		/// 
		/// </summary>
        private decimal? _weight5;
		
		/// <summary>
		/// 
		/// </summary>
        private decimal? _weight6;
		
		 
		#endregion
		
		#region Properties
		
		/// <summary>
		/// 
		/// </summary>
		public string PCEarplugsResilienceWeightId
		{
			get 
			{
				return this._pCEarplugsResilienceWeightId;
			}
			set 
			{
				this._pCEarplugsResilienceWeightId = value;
			}
		}

		/// <summary>
		/// 
		/// </summary>
		public string PCEarplugsResilienceCheckId
		{
			get 
			{
				return this._pCEarplugsResilienceCheckId;
			}
			set 
			{
				this._pCEarplugsResilienceCheckId = value;
			}
		}

		/// <summary>
		/// 
		/// </summary>
		public DateTime? InsertTime
		{
			get 
			{
				return this._insertTime;
			}
			set 
			{
				this._insertTime = value;
			}
		}

		/// <summary>
		/// 
		/// </summary>
		public DateTime? UpdateTime
		{
			get 
			{
				return this._updateTime;
			}
			set 
			{
				this._updateTime = value;
			}
		}

		/// <summary>
		/// 
		/// </summary>
		public decimal? Weight1
		{
			get 
			{
				return this._weight1;
			}
			set 
			{
				this._weight1 = value;
			}
		}

		/// <summary>
		/// 
		/// </summary>
        public decimal? Weight2
		{
			get 
			{
				return this._weight2;
			}
			set 
			{
				this._weight2 = value;
			}
		}

		/// <summary>
		/// 
		/// </summary>
        public decimal? Weight3
		{
			get 
			{
				return this._weight3;
			}
			set 
			{
				this._weight3 = value;
			}
		}

		/// <summary>
		/// 
		/// </summary>
        public decimal? Weight4
		{
			get 
			{
				return this._weight4;
			}
			set 
			{
				this._weight4 = value;
			}
		}

		/// <summary>
		/// 
		/// </summary>
        public decimal? Weight5
		{
			get 
			{
				return this._weight5;
			}
			set 
			{
				this._weight5 = value;
			}
		}

		/// <summary>
		/// 
		/// </summary>
        public decimal? Weight6
		{
			get 
			{
				return this._weight6;
			}
			set 
			{
				this._weight6 = value;
			}
		}
	
		/// <summary>
		/// 
		/// </summary>
		public readonly static string PRO_PCEarplugsResilienceWeightId = "PCEarplugsResilienceWeightId";
		
		/// <summary>
		/// 
		/// </summary>
		public readonly static string PRO_PCEarplugsResilienceCheckId = "PCEarplugsResilienceCheckId";
		
		/// <summary>
		/// 
		/// </summary>
		public readonly static string PRO_InsertTime = "InsertTime";
		
		/// <summary>
		/// 
		/// </summary>
		public readonly static string PRO_UpdateTime = "UpdateTime";
		
		/// <summary>
		/// 
		/// </summary>
		public readonly static string PRO_Weight1 = "Weight1";
		
		/// <summary>
		/// 
		/// </summary>
		public readonly static string PRO_Weight2 = "Weight2";
		
		/// <summary>
		/// 
		/// </summary>
		public readonly static string PRO_Weight3 = "Weight3";
		
		/// <summary>
		/// 
		/// </summary>
		public readonly static string PRO_Weight4 = "Weight4";
		
		/// <summary>
		/// 
		/// </summary>
		public readonly static string PRO_Weight5 = "Weight5";
		
		/// <summary>
		/// 
		/// </summary>
		public readonly static string PRO_Weight6 = "Weight6";
		

		#endregion
	}
}