//------------------------------------------------------------------------------
//
// 说明： 该文件中的内容是由代码生成器自动生成的，请勿手工修改！
//
// file name：PCEuropeOptical.autogenerated.cs
// author: mayanjun
// create date：2015/1/18 下午 08:12:17
//
//------------------------------------------------------------------------------
using System;
namespace Book.Model
{
	public partial class PCEuropeOptical
	{
		#region Data

		/// <summary>
		/// 
		/// </summary>
		private string _pCEuropeOpticalId;
		
		/// <summary>
		/// 
		/// </summary>
		private string _pCDataInputId;
		
		/// <summary>
		/// 
		/// </summary>
		private string _noId;
		
		/// <summary>
		/// 
		/// </summary>
		private decimal? _leftD11;
		
		/// <summary>
		/// 
		/// </summary>
		private decimal? _rightD11;
		
		/// <summary>
		/// 
		/// </summary>
		private decimal? _leftD12;
		
		/// <summary>
		/// 
		/// </summary>
		private decimal? _rightD12;
		
		/// <summary>
		/// 
		/// </summary>
		private decimal? _leftD13;
		
		/// <summary>
		/// 
		/// </summary>
		private decimal? _rightD13;
		
		/// <summary>
		/// 
		/// </summary>
		private decimal? _leftD14;
		
		/// <summary>
		/// 
		/// </summary>
		private decimal? _rightD14;
		
		/// <summary>
		/// 
		/// </summary>
		private decimal? _leftD15;
		
		/// <summary>
		/// 
		/// </summary>
		private decimal? _rightD15;
		
		/// <summary>
		/// 
		/// </summary>
		private decimal? _leftD21;
		
		/// <summary>
		/// 
		/// </summary>
		private decimal? _rightD21;
		
		/// <summary>
		/// 
		/// </summary>
		private decimal? _leftD22;
		
		/// <summary>
		/// 
		/// </summary>
		private decimal? _rightD22;
		
		/// <summary>
		/// 
		/// </summary>
		private decimal? _leftD23;
		
		/// <summary>
		/// 
		/// </summary>
		private decimal? _rightD23;
		
		/// <summary>
		/// 
		/// </summary>
		private decimal? _leftD24;
		
		/// <summary>
		/// 
		/// </summary>
		private decimal? _rightD24;
		
		/// <summary>
		/// 
		/// </summary>
		private decimal? _leftD25;
		
		/// <summary>
		/// 
		/// </summary>
		private decimal? _rightD25;
		
		/// <summary>
		/// 
		/// </summary>
		private string _judge;
		
		/// <summary>
		/// 
		/// </summary>
		private PCDataInput _pCDataInput;
		 
		#endregion
		
		#region Properties
		
		/// <summary>
		/// 
		/// </summary>
		public string PCEuropeOpticalId
		{
			get 
			{
				return this._pCEuropeOpticalId;
			}
			set 
			{
				this._pCEuropeOpticalId = value;
			}
		}

		/// <summary>
		/// 
		/// </summary>
		public string PCDataInputId
		{
			get 
			{
				return this._pCDataInputId;
			}
			set 
			{
				this._pCDataInputId = value;
			}
		}

		/// <summary>
		/// 
		/// </summary>
		public string NoId
		{
			get 
			{
				return this._noId;
			}
			set 
			{
				this._noId = value;
			}
		}

		/// <summary>
		/// 
		/// </summary>
		public decimal? LeftD11
		{
			get 
			{
				return this._leftD11;
			}
			set 
			{
				this._leftD11 = value;
			}
		}

		/// <summary>
		/// 
		/// </summary>
		public decimal? RightD11
		{
			get 
			{
				return this._rightD11;
			}
			set 
			{
				this._rightD11 = value;
			}
		}

		/// <summary>
		/// 
		/// </summary>
		public decimal? LeftD12
		{
			get 
			{
				return this._leftD12;
			}
			set 
			{
				this._leftD12 = value;
			}
		}

		/// <summary>
		/// 
		/// </summary>
		public decimal? RightD12
		{
			get 
			{
				return this._rightD12;
			}
			set 
			{
				this._rightD12 = value;
			}
		}

		/// <summary>
		/// 
		/// </summary>
		public decimal? LeftD13
		{
			get 
			{
				return this._leftD13;
			}
			set 
			{
				this._leftD13 = value;
			}
		}

		/// <summary>
		/// 
		/// </summary>
		public decimal? RightD13
		{
			get 
			{
				return this._rightD13;
			}
			set 
			{
				this._rightD13 = value;
			}
		}

		/// <summary>
		/// 
		/// </summary>
		public decimal? LeftD14
		{
			get 
			{
				return this._leftD14;
			}
			set 
			{
				this._leftD14 = value;
			}
		}

		/// <summary>
		/// 
		/// </summary>
		public decimal? RightD14
		{
			get 
			{
				return this._rightD14;
			}
			set 
			{
				this._rightD14 = value;
			}
		}

		/// <summary>
		/// 
		/// </summary>
		public decimal? LeftD15
		{
			get 
			{
				return this._leftD15;
			}
			set 
			{
				this._leftD15 = value;
			}
		}

		/// <summary>
		/// 
		/// </summary>
		public decimal? RightD15
		{
			get 
			{
				return this._rightD15;
			}
			set 
			{
				this._rightD15 = value;
			}
		}

		/// <summary>
		/// 
		/// </summary>
		public decimal? LeftD21
		{
			get 
			{
				return this._leftD21;
			}
			set 
			{
				this._leftD21 = value;
			}
		}

		/// <summary>
		/// 
		/// </summary>
		public decimal? RightD21
		{
			get 
			{
				return this._rightD21;
			}
			set 
			{
				this._rightD21 = value;
			}
		}

		/// <summary>
		/// 
		/// </summary>
		public decimal? LeftD22
		{
			get 
			{
				return this._leftD22;
			}
			set 
			{
				this._leftD22 = value;
			}
		}

		/// <summary>
		/// 
		/// </summary>
		public decimal? RightD22
		{
			get 
			{
				return this._rightD22;
			}
			set 
			{
				this._rightD22 = value;
			}
		}

		/// <summary>
		/// 
		/// </summary>
		public decimal? LeftD23
		{
			get 
			{
				return this._leftD23;
			}
			set 
			{
				this._leftD23 = value;
			}
		}

		/// <summary>
		/// 
		/// </summary>
		public decimal? RightD23
		{
			get 
			{
				return this._rightD23;
			}
			set 
			{
				this._rightD23 = value;
			}
		}

		/// <summary>
		/// 
		/// </summary>
		public decimal? LeftD24
		{
			get 
			{
				return this._leftD24;
			}
			set 
			{
				this._leftD24 = value;
			}
		}

		/// <summary>
		/// 
		/// </summary>
		public decimal? RightD24
		{
			get 
			{
				return this._rightD24;
			}
			set 
			{
				this._rightD24 = value;
			}
		}

		/// <summary>
		/// 
		/// </summary>
		public decimal? LeftD25
		{
			get 
			{
				return this._leftD25;
			}
			set 
			{
				this._leftD25 = value;
			}
		}

		/// <summary>
		/// 
		/// </summary>
		public decimal? RightD25
		{
			get 
			{
				return this._rightD25;
			}
			set 
			{
				this._rightD25 = value;
			}
		}

		/// <summary>
		/// 
		/// </summary>
		public string Judge
		{
			get 
			{
				return this._judge;
			}
			set 
			{
				this._judge = value;
			}
		}
	
		/// <summary>
		/// 
		/// </summary>
		public virtual PCDataInput PCDataInput
		{
			get
			{
				return this._pCDataInput;
			}
			set
			{
				this._pCDataInput = value;
			}
			
		}
		/// <summary>
		/// 
		/// </summary>
		public readonly static string PRO_PCEuropeOpticalId = "PCEuropeOpticalId";
		
		/// <summary>
		/// 
		/// </summary>
		public readonly static string PRO_PCDataInputId = "PCDataInputId";
		
		/// <summary>
		/// 
		/// </summary>
		public readonly static string PRO_NoId = "NoId";
		
		/// <summary>
		/// 
		/// </summary>
		public readonly static string PRO_LeftD11 = "LeftD11";
		
		/// <summary>
		/// 
		/// </summary>
		public readonly static string PRO_RightD11 = "RightD11";
		
		/// <summary>
		/// 
		/// </summary>
		public readonly static string PRO_LeftD12 = "LeftD12";
		
		/// <summary>
		/// 
		/// </summary>
		public readonly static string PRO_RightD12 = "RightD12";
		
		/// <summary>
		/// 
		/// </summary>
		public readonly static string PRO_LeftD13 = "LeftD13";
		
		/// <summary>
		/// 
		/// </summary>
		public readonly static string PRO_RightD13 = "RightD13";
		
		/// <summary>
		/// 
		/// </summary>
		public readonly static string PRO_LeftD14 = "LeftD14";
		
		/// <summary>
		/// 
		/// </summary>
		public readonly static string PRO_RightD14 = "RightD14";
		
		/// <summary>
		/// 
		/// </summary>
		public readonly static string PRO_LeftD15 = "LeftD15";
		
		/// <summary>
		/// 
		/// </summary>
		public readonly static string PRO_RightD15 = "RightD15";
		
		/// <summary>
		/// 
		/// </summary>
		public readonly static string PRO_LeftD21 = "LeftD21";
		
		/// <summary>
		/// 
		/// </summary>
		public readonly static string PRO_RightD21 = "RightD21";
		
		/// <summary>
		/// 
		/// </summary>
		public readonly static string PRO_LeftD22 = "LeftD22";
		
		/// <summary>
		/// 
		/// </summary>
		public readonly static string PRO_RightD22 = "RightD22";
		
		/// <summary>
		/// 
		/// </summary>
		public readonly static string PRO_LeftD23 = "LeftD23";
		
		/// <summary>
		/// 
		/// </summary>
		public readonly static string PRO_RightD23 = "RightD23";
		
		/// <summary>
		/// 
		/// </summary>
		public readonly static string PRO_LeftD24 = "LeftD24";
		
		/// <summary>
		/// 
		/// </summary>
		public readonly static string PRO_RightD24 = "RightD24";
		
		/// <summary>
		/// 
		/// </summary>
		public readonly static string PRO_LeftD25 = "LeftD25";
		
		/// <summary>
		/// 
		/// </summary>
		public readonly static string PRO_RightD25 = "RightD25";
		
		/// <summary>
		/// 
		/// </summary>
		public readonly static string PRO_Judge = "Judge";
		

		#endregion
	}
}