//------------------------------------------------------------------------------
//
// 说明： 该文件中的内容是由代码生成器自动生成的，请勿手工修改！
//
// file name：PCOpticalMachine.autogenerated.cs
// author: mayanjun
// create date：2015/1/18 下午 08:12:18
//
//------------------------------------------------------------------------------
using System;
namespace Book.Model
{
	public partial class PCOpticalMachine
	{
		#region Data

		/// <summary>
		/// 
		/// </summary>
		private string _pCOpticalMachineId;
		
		/// <summary>
		/// 
		/// </summary>
		private string _pCDataInputId;
		
		/// <summary>
		/// 
		/// </summary>
		private string _noId;
		
		/// <summary>
		/// 
		/// </summary>
		private decimal? _leftS;
		
		/// <summary>
		/// 
		/// </summary>
		private decimal? _rightS;
		
		/// <summary>
		/// 
		/// </summary>
		private decimal? _leftC;
		
		/// <summary>
		/// 
		/// </summary>
		private decimal? _rightC;
		
		/// <summary>
		/// 
		/// </summary>
		private decimal? _leftA;
		
		/// <summary>
		/// 
		/// </summary>
		private decimal? _rightA;
		
		/// <summary>
		/// 
		/// </summary>
		private decimal? _leftLevelNum;
		
		/// <summary>
		/// 
		/// </summary>
		private decimal? _rightLevelNum;
		
		/// <summary>
		/// 
		/// </summary>
		private string _leftLevelJudge;
		
		/// <summary>
		/// 
		/// </summary>
		private string _rightLevelJudge;
		
		/// <summary>
		/// 
		/// </summary>
		private decimal? _leftVerticalNum;
		
		/// <summary>
		/// 
		/// </summary>
		private decimal? _rightVerticalNum;
		
		/// <summary>
		/// 
		/// </summary>
		private string _leftVerticalJudge;
		
		/// <summary>
		/// 
		/// </summary>
		private string _rightVerticalJudge;

        private string _condition;
		
		/// <summary>
		/// 
		/// </summary>
		private PCDataInput _pCDataInput;
		 
		#endregion
		
		#region Properties
		
		/// <summary>
		/// 
		/// </summary>
		public string PCOpticalMachineId
		{
			get 
			{
				return this._pCOpticalMachineId;
			}
			set 
			{
				this._pCOpticalMachineId = value;
			}
		}

		/// <summary>
		/// 
		/// </summary>
		public string PCDataInputId
		{
			get 
			{
				return this._pCDataInputId;
			}
			set 
			{
				this._pCDataInputId = value;
			}
		}

		/// <summary>
		/// 
		/// </summary>
		public string NoId
		{
			get 
			{
				return this._noId;
			}
			set 
			{
				this._noId = value;
			}
		}

		/// <summary>
		/// 
		/// </summary>
		public decimal? LeftS
		{
			get 
			{
				return this._leftS;
			}
			set 
			{
				this._leftS = value;
			}
		}

		/// <summary>
		/// 
		/// </summary>
		public decimal? RightS
		{
			get 
			{
				return this._rightS;
			}
			set 
			{
				this._rightS = value;
			}
		}

		/// <summary>
		/// 
		/// </summary>
		public decimal? LeftC
		{
			get 
			{
				return this._leftC;
			}
			set 
			{
				this._leftC = value;
			}
		}

		/// <summary>
		/// 
		/// </summary>
		public decimal? RightC
		{
			get 
			{
				return this._rightC;
			}
			set 
			{
				this._rightC = value;
			}
		}

		/// <summary>
		/// 
		/// </summary>
		public decimal? LeftA
		{
			get 
			{
				return this._leftA;
			}
			set 
			{
				this._leftA = value;
			}
		}

		/// <summary>
		/// 
		/// </summary>
		public decimal? RightA
		{
			get 
			{
				return this._rightA;
			}
			set 
			{
				this._rightA = value;
			}
		}

		/// <summary>
		/// 
		/// </summary>
		public decimal? LeftLevelNum
		{
			get 
			{
				return this._leftLevelNum;
			}
			set 
			{
				this._leftLevelNum = value;
			}
		}

		/// <summary>
		/// 
		/// </summary>
		public decimal? RightLevelNum
		{
			get 
			{
				return this._rightLevelNum;
			}
			set 
			{
				this._rightLevelNum = value;
			}
		}

		/// <summary>
		/// 
		/// </summary>
		public string LeftLevelJudge
		{
			get 
			{
				return this._leftLevelJudge;
			}
			set 
			{
				this._leftLevelJudge = value;
			}
		}

		/// <summary>
		/// 
		/// </summary>
		public string RightLevelJudge
		{
			get 
			{
				return this._rightLevelJudge;
			}
			set 
			{
				this._rightLevelJudge = value;
			}
		}

		/// <summary>
		/// 
		/// </summary>
		public decimal? LeftVerticalNum
		{
			get 
			{
				return this._leftVerticalNum;
			}
			set 
			{
				this._leftVerticalNum = value;
			}
		}

		/// <summary>
		/// 
		/// </summary>
		public decimal? RightVerticalNum
		{
			get 
			{
				return this._rightVerticalNum;
			}
			set 
			{
				this._rightVerticalNum = value;
			}
		}

		/// <summary>
		/// 
		/// </summary>
		public string LeftVerticalJudge
		{
			get 
			{
				return this._leftVerticalJudge;
			}
			set 
			{
				this._leftVerticalJudge = value;
			}
		}

		/// <summary>
		/// 
		/// </summary>
		public string RightVerticalJudge
		{
			get 
			{
				return this._rightVerticalJudge;
			}
			set 
			{
				this._rightVerticalJudge = value;
			}
		}

        public string Condition
        {
            get { return _condition; }
            set { _condition = value; }
        }
	
		/// <summary>
		/// 
		/// </summary>
		public virtual PCDataInput PCDataInput
		{
			get
			{
				return this._pCDataInput;
			}
			set
			{
				this._pCDataInput = value;
			}
			
		}
		/// <summary>
		/// 
		/// </summary>
		public readonly static string PRO_PCOpticalMachineId = "PCOpticalMachineId";
		
		/// <summary>
		/// 
		/// </summary>
		public readonly static string PRO_PCDataInputId = "PCDataInputId";
		
		/// <summary>
		/// 
		/// </summary>
		public readonly static string PRO_NoId = "NoId";
		
		/// <summary>
		/// 
		/// </summary>
		public readonly static string PRO_LeftS = "LeftS";
		
		/// <summary>
		/// 
		/// </summary>
		public readonly static string PRO_RightS = "RightS";
		
		/// <summary>
		/// 
		/// </summary>
		public readonly static string PRO_LeftC = "LeftC";
		
		/// <summary>
		/// 
		/// </summary>
		public readonly static string PRO_RightC = "RightC";
		
		/// <summary>
		/// 
		/// </summary>
		public readonly static string PRO_LeftA = "LeftA";
		
		/// <summary>
		/// 
		/// </summary>
		public readonly static string PRO_RightA = "RightA";
		
		/// <summary>
		/// 
		/// </summary>
		public readonly static string PRO_LeftLevelNum = "LeftLevelNum";
		
		/// <summary>
		/// 
		/// </summary>
		public readonly static string PRO_RightLevelNum = "RightLevelNum";
		
		/// <summary>
		/// 
		/// </summary>
		public readonly static string PRO_LeftLevelJudge = "LeftLevelJudge";
		
		/// <summary>
		/// 
		/// </summary>
		public readonly static string PRO_RightLevelJudge = "RightLevelJudge";
		
		/// <summary>
		/// 
		/// </summary>
		public readonly static string PRO_LeftVerticalNum = "LeftVerticalNum";
		
		/// <summary>
		/// 
		/// </summary>
		public readonly static string PRO_RightVerticalNum = "RightVerticalNum";
		
		/// <summary>
		/// 
		/// </summary>
		public readonly static string PRO_LeftVerticalJudge = "LeftVerticalJudge";
		
		/// <summary>
		/// 
		/// </summary>
		public readonly static string PRO_RightVerticalJudge = "RightVerticalJudge";

        public readonly static string PRO_Condition = "Condition";

		#endregion
	}
}