//------------------------------------------------------------------------------
//
// 说明： 该文件中的内容是由代码生成器自动生成的，请勿手工修改！
//
// file name：PCPerspective.autogenerated.cs
// author: mayanjun
// create date：2015/1/18 下午 08:12:18
//
//------------------------------------------------------------------------------
using System;
namespace Book.Model
{
	public partial class PCPerspective
	{
		#region Data

		/// <summary>
		/// 
		/// </summary>
		private string _pCPerspectiveId;
		
		/// <summary>
		/// 
		/// </summary>
		private string _pCDataInputId;
		
		/// <summary>
		/// 
		/// </summary>
		private string _noId;
		
		/// <summary>
		/// 
		/// </summary>
		private decimal? _leftT;
		
		/// <summary>
		/// 
		/// </summary>
		private decimal? _rightT;
		
		/// <summary>
		/// 
		/// </summary>
		private string _judge;
		
		/// <summary>
		/// 
		/// </summary>
		private PCDataInput _pCDataInput;
		 
		#endregion
		
		#region Properties
		
		/// <summary>
		/// 
		/// </summary>
		public string PCPerspectiveId
		{
			get 
			{
				return this._pCPerspectiveId;
			}
			set 
			{
				this._pCPerspectiveId = value;
			}
		}

		/// <summary>
		/// 
		/// </summary>
		public string PCDataInputId
		{
			get 
			{
				return this._pCDataInputId;
			}
			set 
			{
				this._pCDataInputId = value;
			}
		}

		/// <summary>
		/// 
		/// </summary>
		public string NoId
		{
			get 
			{
				return this._noId;
			}
			set 
			{
				this._noId = value;
			}
		}

		/// <summary>
		/// 
		/// </summary>
		public decimal? LeftT
		{
			get 
			{
				return this._leftT;
			}
			set 
			{
				this._leftT = value;
			}
		}

		/// <summary>
		/// 
		/// </summary>
		public decimal? RightT
		{
			get 
			{
				return this._rightT;
			}
			set 
			{
				this._rightT = value;
			}
		}

		/// <summary>
		/// 
		/// </summary>
		public string Judge
		{
			get 
			{
				return this._judge;
			}
			set 
			{
				this._judge = value;
			}
		}
	
		/// <summary>
		/// 
		/// </summary>
		public virtual PCDataInput PCDataInput
		{
			get
			{
				return this._pCDataInput;
			}
			set
			{
				this._pCDataInput = value;
			}
			
		}
		/// <summary>
		/// 
		/// </summary>
		public readonly static string PRO_PCPerspectiveId = "PCPerspectiveId";
		
		/// <summary>
		/// 
		/// </summary>
		public readonly static string PRO_PCDataInputId = "PCDataInputId";
		
		/// <summary>
		/// 
		/// </summary>
		public readonly static string PRO_NoId = "NoId";
		
		/// <summary>
		/// 
		/// </summary>
		public readonly static string PRO_LeftT = "LeftT";
		
		/// <summary>
		/// 
		/// </summary>
		public readonly static string PRO_RightT = "RightT";
		
		/// <summary>
		/// 
		/// </summary>
		public readonly static string PRO_Judge = "Judge";
		

		#endregion
	}
}