//------------------------------------------------------------------------------
//
// 说明： 该文件中的内容是由代码生成器自动生成的，请勿手工修改！
//
// file name：XP2.autogenerated.cs
// author: mayanjun
// create date：2015/4/18 下午 12:52:12
//
//------------------------------------------------------------------------------
using System;
namespace Book.Model
{
	public partial class XP2
	{
		#region Data

		/// <summary>
		/// 冲销应付款情况2编号
		/// </summary>
		private string _xP2Id;
		
		/// <summary>
		/// 销售退货编号
		/// </summary>
		private string _invoiceXTId;
		
		/// <summary>
		/// 付款单据编号
		/// </summary>
		private string _invoiceFKId;
		
		/// <summary>
		/// 冲销应付款情况2冲销金额
		/// </summary>
		private decimal? _xP2Money;
		
		/// <summary>
		/// 付款单
		/// </summary>
		private InvoiceFK _invoiceFK;
		/// <summary>
		/// 出货退货单
		/// </summary>
		private InvoiceXT _invoiceXT;
		 
		#endregion
		
		#region Properties
		
		/// <summary>
		/// 冲销应付款情况2编号
		/// </summary>
		public string XP2Id
		{
			get 
			{
				return this._xP2Id;
			}
			set 
			{
				this._xP2Id = value;
			}
		}

		/// <summary>
		/// 销售退货编号
		/// </summary>
		public string InvoiceXTId
		{
			get 
			{
				return this._invoiceXTId;
			}
			set 
			{
				this._invoiceXTId = value;
			}
		}

		/// <summary>
		/// 付款单据编号
		/// </summary>
		public string InvoiceFKId
		{
			get 
			{
				return this._invoiceFKId;
			}
			set 
			{
				this._invoiceFKId = value;
			}
		}

		/// <summary>
		/// 冲销应付款情况2冲销金额
		/// </summary>
		public decimal? XP2Money
		{
			get 
			{
				return this._xP2Money;
			}
			set 
			{
				this._xP2Money = value;
			}
		}
	
		/// <summary>
		/// 付款单
		/// </summary>
		public virtual InvoiceFK InvoiceFK
		{
			get
			{
				return this._invoiceFK;
			}
			set
			{
				this._invoiceFK = value;
			}
			
		}
		/// <summary>
		/// 出货退货单
		/// </summary>
		public virtual InvoiceXT InvoiceXT
		{
			get
			{
				return this._invoiceXT;
			}
			set
			{
				this._invoiceXT = value;
			}
			
		}
		/// <summary>
		/// 冲销应付款情况2编号
		/// </summary>
		public readonly static string PRO_XP2Id = "XP2Id";
		
		/// <summary>
		/// 销售退货编号
		/// </summary>
		public readonly static string PRO_InvoiceXTId = "InvoiceXTId";
		
		/// <summary>
		/// 付款单据编号
		/// </summary>
		public readonly static string PRO_InvoiceFKId = "InvoiceFKId";
		
		/// <summary>
		/// 冲销应付款情况2冲销金额
		/// </summary>
		public readonly static string PRO_XP2Money = "XP2Money";
		

		#endregion
	}
}